using System;
using System.Windows.Forms;
using System.Drawing;
using System.ComponentModel;

namespace GeoBaha
{
    partial class Frm_Project_New
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // Component declarations

        // Controls

        // Button
        private System.Windows.Forms.Button Btn_Save;
        private System.Windows.Forms.Button Button7;
        private System.Windows.Forms.Button btn_Delete;
        private System.Windows.Forms.Button btn_Exit;
        private System.Windows.Forms.Button btn_Filter;
        private System.Windows.Forms.Button btn_Insert;
        private System.Windows.Forms.Button btn_copy;

        // ComboBox
        private System.Windows.Forms.ComboBox cmbo_FehrestName;
        private System.Windows.Forms.ComboBox cmbo_FehrestNameFltr;
        private System.Windows.Forms.ComboBox cmbo_ProjectBakhsh;
        private System.Windows.Forms.ComboBox cmbo_ProjectBakhshFltr;
        private System.Windows.Forms.ComboBox cmbo_ProjectOstan;
        private System.Windows.Forms.ComboBox cmbo_ProjectOstanFltr;
        private System.Windows.Forms.ComboBox cmbo_ProjectShahr;
        private System.Windows.Forms.ComboBox cmbo_ProjectShahrFltr;

        // DataGridView
        private System.Windows.Forms.DataGridView dtg_Project;

        // Label
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.Label Label10;
        private System.Windows.Forms.Label Label35;
        private System.Windows.Forms.Label Label36;
        private System.Windows.Forms.Label Label37;
        private System.Windows.Forms.Label Label38;
        private System.Windows.Forms.Label Label39;
        private System.Windows.Forms.Label Label40;
        private System.Windows.Forms.Label Label41;
        private System.Windows.Forms.Label Label42;
        private System.Windows.Forms.Label lbl_SanadZarib1;
        private System.Windows.Forms.Label lbl_SanadZarib2;
        private System.Windows.Forms.Label lbl_SanadZaribComment1;
        private System.Windows.Forms.Label lbl_SanadZaribComment2;

        // Panel
        private System.Windows.Forms.Panel pnl_Filter;
        private System.Windows.Forms.Panel pnl_Project;

        // PictureBox
        private System.Windows.Forms.PictureBox PictureBox1;

        // TextBox
        private System.Windows.Forms.TextBox txt_ProjectAddress;
        private System.Windows.Forms.TextBox txt_ProjectAddressFltr;
        private System.Windows.Forms.TextBox txt_ProjectCode;
        private System.Windows.Forms.TextBox txt_ProjectCodeFltr;
        private System.Windows.Forms.TextBox txt_ProjectName;
        private System.Windows.Forms.TextBox txt_ProjectNameFltr;
        private System.Windows.Forms.TextBox txt_ProjectTel;
        private System.Windows.Forms.TextBox txt_ProjectTelFltr;

        private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GeoBaha.Frm_Project));
			this.dtg_Project = new System.Windows.Forms.DataGridView();
			this.pnl_Filter = new System.Windows.Forms.Panel();
			this.btn_Filter = new System.Windows.Forms.Button();
			this.Label10 = new System.Windows.Forms.Label();
			this.PictureBox1 = new System.Windows.Forms.PictureBox();
			this.cmbo_FehrestNameFltr = new System.Windows.Forms.ComboBox();
			this.txt_ProjectCodeFltr = new System.Windows.Forms.TextBox();
			this.cmbo_ProjectShahrFltr = new System.Windows.Forms.ComboBox();
			this.cmbo_ProjectBakhshFltr = new System.Windows.Forms.ComboBox();
			this.txt_ProjectNameFltr = new System.Windows.Forms.TextBox();
			this.cmbo_ProjectOstanFltr = new System.Windows.Forms.ComboBox();
			this.txt_ProjectTelFltr = new System.Windows.Forms.TextBox();
			this.txt_ProjectAddressFltr = new System.Windows.Forms.TextBox();
			this.Button7 = new System.Windows.Forms.Button();
			this.pnl_Project = new System.Windows.Forms.Panel();
			this.lbl_SanadZaribComment2 = new System.Windows.Forms.Label();
			this.lbl_SanadZaribComment1 = new System.Windows.Forms.Label();
			this.lbl_SanadZarib2 = new System.Windows.Forms.Label();
			this.lbl_SanadZarib1 = new System.Windows.Forms.Label();
			this.Label39 = new System.Windows.Forms.Label();
			this.cmbo_FehrestName = new System.Windows.Forms.ComboBox();
			this.btn_Exit = new System.Windows.Forms.Button();
			this.btn_Delete = new System.Windows.Forms.Button();
			this.btn_copy = new System.Windows.Forms.Button();
			this.btn_Insert = new System.Windows.Forms.Button();
			this.cmbo_ProjectBakhsh = new System.Windows.Forms.ComboBox();
			this.cmbo_ProjectShahr = new System.Windows.Forms.ComboBox();
			this.cmbo_ProjectOstan = new System.Windows.Forms.ComboBox();
			this.Label42 = new System.Windows.Forms.Label();
			this.Btn_Save = new System.Windows.Forms.Button();
			this.Label41 = new System.Windows.Forms.Label();
			this.Label36 = new System.Windows.Forms.Label();
			this.Label35 = new System.Windows.Forms.Label();
			this.Label40 = new System.Windows.Forms.Label();
			this.txt_ProjectTel = new System.Windows.Forms.TextBox();
			this.txt_ProjectAddress = new System.Windows.Forms.TextBox();
			this.txt_ProjectCode = new System.Windows.Forms.TextBox();
			this.txt_ProjectName = new System.Windows.Forms.TextBox();
			this.Label38 = new System.Windows.Forms.Label();
			this.Label37 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			((System.ComponentModel.ISupportInitialize)this.dtg_Project).BeginInit();
			this.pnl_Filter.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.pnl_Project.SuspendLayout();
			base.SuspendLayout();
			this.dtg_Project.AllowUserToAddRows = false;
			this.dtg_Project.AllowUserToDeleteRows = false;
			this.dtg_Project.AllowUserToOrderColumns = true;
			this.dtg_Project.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
			this.dtg_Project.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.dtg_Project.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.dtg_Project.Location = new System.Drawing.Point(5, 24);
			this.dtg_Project.Name = "dtg_Project";
			this.dtg_Project.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.dtg_Project.RowTemplate.DefaultCellStyle.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.dtg_Project.RowTemplate.DefaultCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dtg_Project.RowTemplate.Height = 44;
			this.dtg_Project.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
			this.dtg_Project.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dtg_Project.Size = new System.Drawing.Size(1180, 520);
			this.dtg_Project.TabIndex = 87;
			this.pnl_Filter.Controls.Add(this.btn_Filter);
			this.pnl_Filter.Controls.Add(this.Label10);
			this.pnl_Filter.Controls.Add(this.PictureBox1);
			this.pnl_Filter.Controls.Add(this.cmbo_FehrestNameFltr);
			this.pnl_Filter.Controls.Add(this.txt_ProjectCodeFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ProjectShahrFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ProjectBakhshFltr);
			this.pnl_Filter.Controls.Add(this.txt_ProjectNameFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ProjectOstanFltr);
			this.pnl_Filter.Controls.Add(this.txt_ProjectTelFltr);
			this.pnl_Filter.Controls.Add(this.txt_ProjectAddressFltr);
			this.pnl_Filter.Controls.Add(this.Button7);
			this.pnl_Filter.Location = new System.Drawing.Point(5, 11);
			this.pnl_Filter.Name = "pnl_Filter";
			this.pnl_Filter.Size = new System.Drawing.Size(1168, 48);
			this.pnl_Filter.TabIndex = 88;
			this.btn_Filter.BackColor = System.Drawing.Color.White;
			this.btn_Filter.Font = new System.Drawing.Font("Times New Roman", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.btn_Filter.ForeColor = System.Drawing.Color.Black;
			this.btn_Filter.Location = new System.Drawing.Point(1126, 0);
			this.btn_Filter.Name = "btn_Filter";
			this.btn_Filter.Size = new System.Drawing.Size(40, 47);
			this.btn_Filter.TabIndex = 94;
			this.btn_Filter.UseVisualStyleBackColor = false;
			this.Label10.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.Label10.BackColor = System.Drawing.Color.White;
			this.Label10.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label10.Location = new System.Drawing.Point(1065, 0);
			this.Label10.Name = "Label10";
			this.Label10.Size = new System.Drawing.Size(61, 46);
			this.Label10.TabIndex = 155;
			this.Label10.Text = "ردیف";
			this.Label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.PictureBox1.Image = (System.Drawing.Image)resources.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new System.Drawing.Point(3, -7);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new System.Drawing.Size(1162, 31);
			this.PictureBox1.TabIndex = 156;
			this.PictureBox1.TabStop = false;
			this.cmbo_FehrestNameFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_FehrestNameFltr.FormattingEnabled = true;
			this.cmbo_FehrestNameFltr.Location = new System.Drawing.Point(4, 25);
			this.cmbo_FehrestNameFltr.Name = "cmbo_FehrestNameFltr";
			this.cmbo_FehrestNameFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_FehrestNameFltr.Size = new System.Drawing.Size(139, 21);
			this.cmbo_FehrestNameFltr.TabIndex = 85;
			this.txt_ProjectCodeFltr.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectCodeFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ProjectCodeFltr.Location = new System.Drawing.Point(1005, 25);
			this.txt_ProjectCodeFltr.Name = "txt_ProjectCodeFltr";
			this.txt_ProjectCodeFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectCodeFltr.Size = new System.Drawing.Size(59, 21);
			this.txt_ProjectCodeFltr.TabIndex = 78;
			this.cmbo_ProjectShahrFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ProjectShahrFltr.FormattingEnabled = true;
			this.cmbo_ProjectShahrFltr.Location = new System.Drawing.Point(543, 25);
			this.cmbo_ProjectShahrFltr.Name = "cmbo_ProjectShahrFltr";
			this.cmbo_ProjectShahrFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectShahrFltr.Size = new System.Drawing.Size(99, 21);
			this.cmbo_ProjectShahrFltr.TabIndex = 81;
			this.cmbo_ProjectBakhshFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ProjectBakhshFltr.FormattingEnabled = true;
			this.cmbo_ProjectBakhshFltr.Location = new System.Drawing.Point(443, 25);
			this.cmbo_ProjectBakhshFltr.Name = "cmbo_ProjectBakhshFltr";
			this.cmbo_ProjectBakhshFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectBakhshFltr.Size = new System.Drawing.Size(100, 21);
			this.cmbo_ProjectBakhshFltr.TabIndex = 82;
			this.txt_ProjectNameFltr.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectNameFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ProjectNameFltr.Location = new System.Drawing.Point(744, 25);
			this.txt_ProjectNameFltr.Name = "txt_ProjectNameFltr";
			this.txt_ProjectNameFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectNameFltr.Size = new System.Drawing.Size(260, 21);
			this.txt_ProjectNameFltr.TabIndex = 79;
			this.cmbo_ProjectOstanFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ProjectOstanFltr.FormattingEnabled = true;
			this.cmbo_ProjectOstanFltr.Location = new System.Drawing.Point(643, 25);
			this.cmbo_ProjectOstanFltr.Name = "cmbo_ProjectOstanFltr";
			this.cmbo_ProjectOstanFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectOstanFltr.Size = new System.Drawing.Size(100, 21);
			this.cmbo_ProjectOstanFltr.TabIndex = 80;
			this.txt_ProjectTelFltr.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectTelFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ProjectTelFltr.Location = new System.Drawing.Point(144, 25);
			this.txt_ProjectTelFltr.Name = "txt_ProjectTelFltr";
			this.txt_ProjectTelFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectTelFltr.Size = new System.Drawing.Size(98, 21);
			this.txt_ProjectTelFltr.TabIndex = 84;
			this.txt_ProjectAddressFltr.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectAddressFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ProjectAddressFltr.Location = new System.Drawing.Point(242, 25);
			this.txt_ProjectAddressFltr.Name = "txt_ProjectAddressFltr";
			this.txt_ProjectAddressFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectAddressFltr.Size = new System.Drawing.Size(201, 21);
			this.txt_ProjectAddressFltr.TabIndex = 83;
			this.Button7.BackColor = System.Drawing.Color.LightGray;
			this.Button7.Font = new System.Drawing.Font("Times New Roman", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.Button7.ForeColor = System.Drawing.Color.Black;
			this.Button7.Location = new System.Drawing.Point(1506, 7);
			this.Button7.Name = "Button7";
			this.Button7.Size = new System.Drawing.Size(89, 21);
			this.Button7.TabIndex = 44;
			this.Button7.Text = "حذف فیلتر";
			this.Button7.UseVisualStyleBackColor = false;
			this.pnl_Project.BackColor = System.Drawing.Color.LightSteelBlue;
			this.pnl_Project.Controls.Add(this.lbl_SanadZaribComment2);
			this.pnl_Project.Controls.Add(this.lbl_SanadZaribComment1);
			this.pnl_Project.Controls.Add(this.lbl_SanadZarib2);
			this.pnl_Project.Controls.Add(this.lbl_SanadZarib1);
			this.pnl_Project.Controls.Add(this.Label39);
			this.pnl_Project.Controls.Add(this.cmbo_FehrestName);
			this.pnl_Project.Controls.Add(this.btn_Exit);
			this.pnl_Project.Controls.Add(this.btn_Delete);
			this.pnl_Project.Controls.Add(this.btn_copy);
			this.pnl_Project.Controls.Add(this.btn_Insert);
			this.pnl_Project.Controls.Add(this.cmbo_ProjectBakhsh);
			this.pnl_Project.Controls.Add(this.cmbo_ProjectShahr);
			this.pnl_Project.Controls.Add(this.cmbo_ProjectOstan);
			this.pnl_Project.Controls.Add(this.Label42);
			this.pnl_Project.Controls.Add(this.Btn_Save);
			this.pnl_Project.Controls.Add(this.Label41);
			this.pnl_Project.Controls.Add(this.Label36);
			this.pnl_Project.Controls.Add(this.Label35);
			this.pnl_Project.Controls.Add(this.Label40);
			this.pnl_Project.Controls.Add(this.txt_ProjectTel);
			this.pnl_Project.Controls.Add(this.txt_ProjectAddress);
			this.pnl_Project.Controls.Add(this.txt_ProjectCode);
			this.pnl_Project.Controls.Add(this.txt_ProjectName);
			this.pnl_Project.Controls.Add(this.Label38);
			this.pnl_Project.Controls.Add(this.Label37);
			this.pnl_Project.Controls.Add(this.Label1);
			this.pnl_Project.Location = new System.Drawing.Point(5, 546);
			this.pnl_Project.Name = "pnl_Project";
			this.pnl_Project.Size = new System.Drawing.Size(1179, 143);
			this.pnl_Project.TabIndex = 92;
			this.lbl_SanadZaribComment2.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZaribComment2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZaribComment2.Location = new System.Drawing.Point(15, 78);
			this.lbl_SanadZaribComment2.Name = "lbl_SanadZaribComment2";
			this.lbl_SanadZaribComment2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZaribComment2.Size = new System.Drawing.Size(368, 20);
			this.lbl_SanadZaribComment2.TabIndex = 140;
			this.lbl_SanadZaribComment2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadZaribComment1.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZaribComment1.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZaribComment1.Location = new System.Drawing.Point(15, 55);
			this.lbl_SanadZaribComment1.Name = "lbl_SanadZaribComment1";
			this.lbl_SanadZaribComment1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZaribComment1.Size = new System.Drawing.Size(368, 20);
			this.lbl_SanadZaribComment1.TabIndex = 139;
			this.lbl_SanadZaribComment1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadZarib2.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZarib2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZarib2.Location = new System.Drawing.Point(387, 78);
			this.lbl_SanadZarib2.Name = "lbl_SanadZarib2";
			this.lbl_SanadZarib2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZarib2.Size = new System.Drawing.Size(43, 20);
			this.lbl_SanadZarib2.TabIndex = 138;
			this.lbl_SanadZarib2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.lbl_SanadZarib1.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZarib1.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZarib1.Location = new System.Drawing.Point(387, 55);
			this.lbl_SanadZarib1.Name = "lbl_SanadZarib1";
			this.lbl_SanadZarib1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZarib1.Size = new System.Drawing.Size(43, 20);
			this.lbl_SanadZarib1.TabIndex = 137;
			this.lbl_SanadZarib1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.Label39.Location = new System.Drawing.Point(428, 69);
			this.Label39.Name = "Label39";
			this.Label39.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label39.Size = new System.Drawing.Size(91, 27);
			this.Label39.TabIndex = 136;
			this.Label39.Text = " :ضریب منطقه ای";
			this.cmbo_FehrestName.Enabled = false;
			this.cmbo_FehrestName.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_FehrestName.FormattingEnabled = true;
			this.cmbo_FehrestName.Location = new System.Drawing.Point(14, 22);
			this.cmbo_FehrestName.Name = "cmbo_FehrestName";
			this.cmbo_FehrestName.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_FehrestName.Size = new System.Drawing.Size(273, 26);
			this.cmbo_FehrestName.TabIndex = 125;
			this.btn_Exit.Location = new System.Drawing.Point(65, 110);
			this.btn_Exit.Name = "btn_Exit";
			this.btn_Exit.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Exit.Size = new System.Drawing.Size(100, 28);
			this.btn_Exit.TabIndex = 127;
			this.btn_Exit.Text = " خروج ";
			this.btn_Exit.UseVisualStyleBackColor = true;
			this.btn_Delete.Location = new System.Drawing.Point(295, 110);
			this.btn_Delete.Name = "btn_Delete";
			this.btn_Delete.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Delete.Size = new System.Drawing.Size(100, 28);
			this.btn_Delete.TabIndex = 132;
			this.btn_Delete.Text = "(Del) حذف";
			this.btn_Delete.UseVisualStyleBackColor = true;
			this.btn_copy.Location = new System.Drawing.Point(532, 110);
			this.btn_copy.Name = "btn_copy";
			this.btn_copy.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_copy.Size = new System.Drawing.Size(100, 28);
			this.btn_copy.TabIndex = 131;
			this.btn_copy.Text = "(Clt+C) کپی";
			this.btn_copy.UseVisualStyleBackColor = true;
			this.btn_Insert.Location = new System.Drawing.Point(760, 110);
			this.btn_Insert.Name = "btn_Insert";
			this.btn_Insert.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Insert.Size = new System.Drawing.Size(100, 28);
			this.btn_Insert.TabIndex = 130;
			this.btn_Insert.Text = "(Ins) ایجاد ";
			this.btn_Insert.UseVisualStyleBackColor = true;
			this.cmbo_ProjectBakhsh.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ProjectBakhsh.FormattingEnabled = true;
			this.cmbo_ProjectBakhsh.Location = new System.Drawing.Point(291, 23);
			this.cmbo_ProjectBakhsh.Name = "cmbo_ProjectBakhsh";
			this.cmbo_ProjectBakhsh.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectBakhsh.Size = new System.Drawing.Size(100, 26);
			this.cmbo_ProjectBakhsh.TabIndex = 122;
			this.cmbo_ProjectShahr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ProjectShahr.FormattingEnabled = true;
			this.cmbo_ProjectShahr.Location = new System.Drawing.Point(392, 23);
			this.cmbo_ProjectShahr.Name = "cmbo_ProjectShahr";
			this.cmbo_ProjectShahr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectShahr.Size = new System.Drawing.Size(100, 26);
			this.cmbo_ProjectShahr.TabIndex = 121;
			this.cmbo_ProjectOstan.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ProjectOstan.FormattingEnabled = true;
			this.cmbo_ProjectOstan.Location = new System.Drawing.Point(493, 23);
			this.cmbo_ProjectOstan.Name = "cmbo_ProjectOstan";
			this.cmbo_ProjectOstan.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ProjectOstan.Size = new System.Drawing.Size(100, 26);
			this.cmbo_ProjectOstan.TabIndex = 120;
			this.Label42.AutoSize = true;
			this.Label42.Location = new System.Drawing.Point(336, 7);
			this.Label42.Name = "Label42";
			this.Label42.Size = new System.Drawing.Size(30, 13);
			this.Label42.TabIndex = 115;
			this.Label42.Text = " بخش";
			this.Btn_Save.Location = new System.Drawing.Point(981, 110);
			this.Btn_Save.Name = "Btn_Save";
			this.Btn_Save.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Save.Size = new System.Drawing.Size(100, 28);
			this.Btn_Save.TabIndex = 126;
			this.Btn_Save.Text = "(F2) ذخیره ";
			this.Btn_Save.UseVisualStyleBackColor = true;
			this.Label41.AutoSize = true;
			this.Label41.Location = new System.Drawing.Point(423, 7);
			this.Label41.Name = "Label41";
			this.Label41.Size = new System.Drawing.Size(54, 13);
			this.Label41.TabIndex = 117;
			this.Label41.Text = " شهرستان";
			this.Label36.AutoSize = true;
			this.Label36.Location = new System.Drawing.Point(813, 7);
			this.Label36.Name = "Label36";
			this.Label36.Size = new System.Drawing.Size(55, 13);
			this.Label36.TabIndex = 123;
			this.Label36.Text = " نام پروژه ";
			this.Label35.AutoSize = true;
			this.Label35.Location = new System.Drawing.Point(1071, 7);
			this.Label35.Name = "Label35";
			this.Label35.Size = new System.Drawing.Size(51, 13);
			this.Label35.TabIndex = 122;
			this.Label35.Text = "کد پروژه ";
			this.Label40.AutoSize = true;
			this.Label40.Location = new System.Drawing.Point(530, 7);
			this.Label40.Name = "Label40";
			this.Label40.Size = new System.Drawing.Size(37, 13);
			this.Label40.TabIndex = 119;
			this.Label40.Text = "استان ";
			this.txt_ProjectTel.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectTel.Location = new System.Drawing.Point(545, 63);
			this.txt_ProjectTel.Name = "txt_ProjectTel";
			this.txt_ProjectTel.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectTel.Size = new System.Drawing.Size(97, 26);
			this.txt_ProjectTel.TabIndex = 124;
			this.txt_ProjectAddress.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectAddress.Location = new System.Drawing.Point(715, 63);
			this.txt_ProjectAddress.Name = "txt_ProjectAddress";
			this.txt_ProjectAddress.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectAddress.Size = new System.Drawing.Size(350, 26);
			this.txt_ProjectAddress.TabIndex = 123;
			this.txt_ProjectCode.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectCode.Location = new System.Drawing.Point(1066, 23);
			this.txt_ProjectCode.Name = "txt_ProjectCode";
			this.txt_ProjectCode.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectCode.Size = new System.Drawing.Size(59, 26);
			this.txt_ProjectCode.TabIndex = 118;
			this.txt_ProjectName.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectName.Location = new System.Drawing.Point(595, 23);
			this.txt_ProjectName.Name = "txt_ProjectName";
			this.txt_ProjectName.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectName.Size = new System.Drawing.Size(470, 26);
			this.txt_ProjectName.TabIndex = 119;
			this.Label38.AutoSize = true;
			this.Label38.Location = new System.Drawing.Point(640, 69);
			this.Label38.Name = "Label38";
			this.Label38.Size = new System.Drawing.Size(61, 13);
			this.Label38.TabIndex = 125;
			this.Label38.Text = " تلفن پروژه:";
			this.Label37.AutoSize = true;
			this.Label37.Location = new System.Drawing.Point(1063, 67);
			this.Label37.Name = "Label37";
			this.Label37.Size = new System.Drawing.Size(68, 13);
			this.Label37.TabIndex = 124;
			this.Label37.Text = " آدرس پروژه :";
			this.Label1.AutoSize = true;
			this.Label1.Location = new System.Drawing.Point(142, 7);
			this.Label1.Name = "Label1";
			this.Label1.Size = new System.Drawing.Size(61, 13);
			this.Label1.TabIndex = 135;
			this.Label1.Text = "فهرست بها:";
			base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.AutoScroll = true;
			this.BackColor = System.Drawing.Color.LightSteelBlue;
			base.ClientSize = new System.Drawing.Size(1190, 692);
			base.ControlBox = false;
			base.Controls.Add(this.pnl_Filter);
			base.Controls.Add(this.pnl_Project);
			base.Controls.Add(this.dtg_Project);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.Fixed3D;
			base.Location = new System.Drawing.Point(90, 105);
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "Frm_Project";
			this.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.RightToLeftLayout = true;
			base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "لیست پروژه ها";
			((System.ComponentModel.ISupportInitialize)this.dtg_Project).EndInit();
			this.pnl_Filter.ResumeLayout(false);
			this.pnl_Filter.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.pnl_Project.ResumeLayout(false);
			this.pnl_Project.PerformLayout();
			base.ResumeLayout(false);

            this.dtg_Project.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_projectList_CellClick);
            this.dtg_Project.CellContentDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_projectList_CellContentDoubleClick);
            this.dtg_Project.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_projectList_CellDoubleClick);
            this.dtg_Project.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_projectList_CellContentClick);
            this.dtg_Project.SelectionChanged += new System.EventHandler(this.dtg_project_SelectionChanged);
            this.dtg_Project.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dtg_Project_KeyDown);
            this.cmbo_ProjectShahrFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_ProjectShahrFltr_SelectedIndexChanged);
            this.cmbo_ProjectShahrFltr.TextChanged += new System.EventHandler(this.cmbo_ProjectShahrFltr_TextChanged);
            this.cmbo_ProjectBakhshFltr.TextChanged += new System.EventHandler(this.cmbo_ProjectBakhshFltr_TextChanged);
            this.txt_ProjectNameFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ProjectNameFltr_KeyDown);
            this.cmbo_ProjectOstanFltr.TextChanged += new System.EventHandler(this.cmbo_ProjectOstanFltr_TextChanged);
            this.txt_ProjectTelFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ProjectTelFltr_KeyDown);
            this.txt_ProjectAddressFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ProjectAddressFltr_KeyDown);
            this.txt_ProjectCodeFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ProjectCodeFltr_KeyDown);
            this.btn_Exit.Click += new System.EventHandler(this.btn_Exit_Click);
            this.btn_Delete.Click += new System.EventHandler(this.btn_Delete_Click);
            this.btn_copy.Click += new System.EventHandler(this.btn_copy_Click);
            this.btn_Insert.Click += new System.EventHandler(this.btn_Insert_Click);
            this.cmbo_ProjectBakhsh.GotFocus += new System.EventHandler(this.cmbo_ProjectBakhsh_GotFocus);
            this.cmbo_ProjectBakhsh.MouseClick += new System.Windows.Forms.MouseEventHandler(this.cmbo_ProjectBakhsh_MouseClick);
            this.cmbo_ProjectBakhsh.TextChanged += new System.EventHandler(this.cmbo_ProjectBakhsh_TextChanged);
            this.cmbo_ProjectBakhsh.SelectedIndexChanged += new System.EventHandler(this.cmbo_ProjectBakhsh_SelectedIndexChanged);
            this.cmbo_ProjectShahr.GotFocus += new System.EventHandler(this.cmbo_ProjectShahr_GotFocus);
            this.cmbo_ProjectShahr.SelectedValueChanged += new System.EventHandler(this.cmbo_ProjectShahr_SelectedValueChanged);
            this.cmbo_ProjectShahr.TextChanged += new System.EventHandler(this.cmbo_ProjectShahr_TextChanged);
            this.cmbo_ProjectShahr.SelectedIndexChanged += new System.EventHandler(this.cmbo_ProjectShahr_SelectedIndexChanged);
            this.cmbo_ProjectOstan.GotFocus += new System.EventHandler(this.cmbo_ProjectOstan_GotFocus);
            this.cmbo_ProjectOstan.TextChanged += new System.EventHandler(this.cmbo_ProjectOstan_TextChanged);
            this.cmbo_ProjectOstan.SelectedIndexChanged += new System.EventHandler(this.cmbo_ProjectOstan_SelectedIndexChanged);
            this.Btn_Save.Click += new System.EventHandler(this.Btn_Save_Click);
            this.txt_ProjectTel.GotFocus += new System.EventHandler(this.txt_ProjectTelList_GotFocus);
            this.txt_ProjectTel.TextChanged += new System.EventHandler(this.txt_ProjectTelList_TextChanged);
            this.txt_ProjectAddress.GotFocus += new System.EventHandler(this.txt_ProjectAddressList_GotFocus);
            this.txt_ProjectAddress.TextChanged += new System.EventHandler(this.txt_ProjectAddressList_TextChanged);
            this.txt_ProjectCode.GotFocus += new System.EventHandler(this.txt_ProjectCodeList_GotFocus);
            this.txt_ProjectCode.TextChanged += new System.EventHandler(this.txt_ProjectCodeList_TextChanged);
            this.txt_ProjectName.GotFocus += new System.EventHandler(this.txt_ProjectList_GotFocus);
            this.txt_ProjectName.TextChanged += new System.EventHandler(this.txt_ProjectList_TextChanged);
            this.btn_Filter.Click += new System.EventHandler(this.btn_Filter_Click);
            this.cmbo_FehrestNameFltr.TextChanged += new System.EventHandler(this.cmbo_FehrestFltr_TextChanged);
            this.cmbo_FehrestName.GotFocus += new System.EventHandler(this.cmbo_FehrestName_GotFocus);
            this.cmbo_FehrestName.TextChanged += new System.EventHandler(this.cmbo_FehrestName_TextChanged);
        }
    }
}
