using System;
using System.Windows.Forms;
using System.Drawing;
using System.ComponentModel;

namespace GeoBaha
{
    partial class Frm_AsnadList_New
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // Component declarations

        // Controls

        // Button
        private System.Windows.Forms.Button Btn_Open;
        private System.Windows.Forms.Button Btn_Save;
        private System.Windows.Forms.Button btn_Copy;
        private System.Windows.Forms.Button btn_Delete;
        private System.Windows.Forms.Button btn_Exit;
        private System.Windows.Forms.Button btn_Filter;
        private System.Windows.Forms.Button btn_Insert;
        private System.Windows.Forms.Button btn_KarfarmaSearch;
        private System.Windows.Forms.Button btn_OnvanCode;
        private System.Windows.Forms.Button btn_projectSearch;

        // CheckBox
        private System.Windows.Forms.CheckBox chk_SabtNashode;

        // ComboBox
        private System.Windows.Forms.ComboBox cmbo_Amaliat;
        private System.Windows.Forms.ComboBox cmbo_FehrestFltr;
        private System.Windows.Forms.ComboBox cmbo_FehrestName;
        private System.Windows.Forms.ComboBox cmbo_NoaSanadFltr;
        private System.Windows.Forms.ComboBox cmbo_OnvanCode;
        private System.Windows.Forms.ComboBox cmbo_SalMali;
        private System.Windows.Forms.ComboBox cmbo_SalMaliFltr;
        private System.Windows.Forms.ComboBox cmbo_SanadNoa;

        // DataGridView
        private System.Windows.Forms.DataGridView dtg_AsnadList;

        // DateTimePicker
        private System.Windows.Forms.DateTimePicker DateTimePicker1;

        // Label
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.Label Label10;
        private System.Windows.Forms.Label Label16;
        private System.Windows.Forms.Label Label17;
        private System.Windows.Forms.Label Label18;
        private System.Windows.Forms.Label Label2;
        private System.Windows.Forms.Label Label22;
        private System.Windows.Forms.Label Label26;
        private System.Windows.Forms.Label Label28;
        private System.Windows.Forms.Label Label3;
        private System.Windows.Forms.Label Label32;
        private System.Windows.Forms.Label Label33;
        private System.Windows.Forms.Label Label34;
        private System.Windows.Forms.Label Label39;
        private System.Windows.Forms.Label Label4;
        private System.Windows.Forms.Label Label40;
        private System.Windows.Forms.Label Label41;
        private System.Windows.Forms.Label Label42;
        private System.Windows.Forms.Label Label5;
        private System.Windows.Forms.Label Label6;
        private System.Windows.Forms.Label Label8;
        private System.Windows.Forms.Label Label9;
        private System.Windows.Forms.Label lbl_AsnadNum;
        private System.Windows.Forms.Label lbl_AsnadSum;
        private System.Windows.Forms.Label lbl_Baha;
        private System.Windows.Forms.Label lbl_SanadBakhsh;
        private System.Windows.Forms.Label lbl_SanadBakhshCode;
        private System.Windows.Forms.Label lbl_SanadOstan;
        private System.Windows.Forms.Label lbl_SanadShahr;
        private System.Windows.Forms.Label lbl_SanadZarib1;
        private System.Windows.Forms.Label lbl_SanadZarib2;
        private System.Windows.Forms.Label lbl_SanadZaribComment1;
        private System.Windows.Forms.Label lbl_SanadZaribComment2;
        private System.Windows.Forms.Label lbl_User;

        // Panel
        private System.Windows.Forms.Panel Panel1;
        private System.Windows.Forms.Panel Panel8;
        private System.Windows.Forms.Panel pnl_Asnad;
        private System.Windows.Forms.Panel pnl_Filter;

        // PictureBox
        private System.Windows.Forms.PictureBox PictureBox1;

        // TextBox
        private System.Windows.Forms.TextBox txt_AmaliatFltr;
        private System.Windows.Forms.TextBox txt_BahaFltr;
        private System.Windows.Forms.TextBox txt_Comment;
        private System.Windows.Forms.TextBox txt_CommentFltr;
        private System.Windows.Forms.TextBox txt_JobNo;
        private System.Windows.Forms.TextBox txt_JobNoFltr;
        private System.Windows.Forms.TextBox txt_Karfarma;
        private System.Windows.Forms.TextBox txt_KarfarmaFltr;
        private System.Windows.Forms.TextBox txt_Project;
        private System.Windows.Forms.TextBox txt_ProjectFltr;
        private System.Windows.Forms.TextBox txt_Roonevesht;
        private System.Windows.Forms.TextBox txt_SanadDateFltr;
        private System.Windows.Forms.TextBox txt_SanadDay;
        private System.Windows.Forms.TextBox txt_SanadMonth;
        private System.Windows.Forms.TextBox txt_SanadNo;
        private System.Windows.Forms.TextBox txt_SanadNoFltr;
        private System.Windows.Forms.TextBox txt_SanadYear;

        private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GeoBaha.Frm_AsnadList));
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
			this.pnl_Filter = new System.Windows.Forms.Panel();
			this.btn_Filter = new System.Windows.Forms.Button();
			this.Label10 = new System.Windows.Forms.Label();
			this.PictureBox1 = new System.Windows.Forms.PictureBox();
			this.cmbo_SalMaliFltr = new System.Windows.Forms.ComboBox();
			this.cmbo_FehrestFltr = new System.Windows.Forms.ComboBox();
			this.cmbo_NoaSanadFltr = new System.Windows.Forms.ComboBox();
			this.txt_CommentFltr = new System.Windows.Forms.TextBox();
			this.txt_KarfarmaFltr = new System.Windows.Forms.TextBox();
			this.txt_ProjectFltr = new System.Windows.Forms.TextBox();
			this.txt_SanadDateFltr = new System.Windows.Forms.TextBox();
			this.txt_JobNoFltr = new System.Windows.Forms.TextBox();
			this.txt_SanadNoFltr = new System.Windows.Forms.TextBox();
			this.txt_BahaFltr = new System.Windows.Forms.TextBox();
			this.txt_AmaliatFltr = new System.Windows.Forms.TextBox();
			this.pnl_Asnad = new System.Windows.Forms.Panel();
			this.txt_SanadNo = new System.Windows.Forms.TextBox();
			this.txt_Karfarma = new System.Windows.Forms.TextBox();
			this.txt_Project = new System.Windows.Forms.TextBox();
			this.btn_KarfarmaSearch = new System.Windows.Forms.Button();
			this.btn_projectSearch = new System.Windows.Forms.Button();
			this.DateTimePicker1 = new System.Windows.Forms.DateTimePicker();
			this.txt_SanadYear = new System.Windows.Forms.TextBox();
			this.txt_SanadMonth = new System.Windows.Forms.TextBox();
			this.txt_SanadDay = new System.Windows.Forms.TextBox();
			this.Label16 = new System.Windows.Forms.Label();
			this.Label17 = new System.Windows.Forms.Label();
			this.Label18 = new System.Windows.Forms.Label();
			this.btn_Delete = new System.Windows.Forms.Button();
			this.btn_OnvanCode = new System.Windows.Forms.Button();
			this.Btn_Open = new System.Windows.Forms.Button();
			this.cmbo_Amaliat = new System.Windows.Forms.ComboBox();
			this.cmbo_OnvanCode = new System.Windows.Forms.ComboBox();
			this.cmbo_SalMali = new System.Windows.Forms.ComboBox();
			this.Label5 = new System.Windows.Forms.Label();
			this.lbl_Baha = new System.Windows.Forms.Label();
			this.btn_Exit = new System.Windows.Forms.Button();
			this.btn_Copy = new System.Windows.Forms.Button();
			this.btn_Insert = new System.Windows.Forms.Button();
			this.Btn_Save = new System.Windows.Forms.Button();
			this.Panel8 = new System.Windows.Forms.Panel();
			this.lbl_SanadBakhshCode = new System.Windows.Forms.Label();
			this.lbl_SanadZaribComment2 = new System.Windows.Forms.Label();
			this.lbl_SanadZaribComment1 = new System.Windows.Forms.Label();
			this.lbl_SanadZarib2 = new System.Windows.Forms.Label();
			this.lbl_SanadZarib1 = new System.Windows.Forms.Label();
			this.lbl_SanadBakhsh = new System.Windows.Forms.Label();
			this.lbl_SanadShahr = new System.Windows.Forms.Label();
			this.lbl_SanadOstan = new System.Windows.Forms.Label();
			this.Label39 = new System.Windows.Forms.Label();
			this.Label40 = new System.Windows.Forms.Label();
			this.Label41 = new System.Windows.Forms.Label();
			this.Label42 = new System.Windows.Forms.Label();
			this.cmbo_FehrestName = new System.Windows.Forms.ComboBox();
			this.Label34 = new System.Windows.Forms.Label();
			this.Label32 = new System.Windows.Forms.Label();
			this.cmbo_SanadNoa = new System.Windows.Forms.ComboBox();
			this.Label9 = new System.Windows.Forms.Label();
			this.txt_JobNo = new System.Windows.Forms.TextBox();
			this.txt_Comment = new System.Windows.Forms.TextBox();
			this.Label33 = new System.Windows.Forms.Label();
			this.Label8 = new System.Windows.Forms.Label();
			this.Label22 = new System.Windows.Forms.Label();
			this.Label1 = new System.Windows.Forms.Label();
			this.Label2 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.Label3 = new System.Windows.Forms.Label();
			this.Panel1 = new System.Windows.Forms.Panel();
			this.lbl_AsnadSum = new System.Windows.Forms.Label();
			this.lbl_AsnadNum = new System.Windows.Forms.Label();
			this.Label26 = new System.Windows.Forms.Label();
			this.Label28 = new System.Windows.Forms.Label();
			this.dtg_AsnadList = new System.Windows.Forms.DataGridView();
			this.txt_Roonevesht = new System.Windows.Forms.TextBox();
			this.lbl_User = new System.Windows.Forms.Label();
			this.chk_SabtNashode = new System.Windows.Forms.CheckBox();
			this.Label6 = new System.Windows.Forms.Label();
			this.pnl_Filter.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.pnl_Asnad.SuspendLayout();
			this.Panel8.SuspendLayout();
			this.Panel1.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_AsnadList).BeginInit();
			base.SuspendLayout();
			this.pnl_Filter.BackColor = System.Drawing.Color.White;
			this.pnl_Filter.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnl_Filter.Controls.Add(this.btn_Filter);
			this.pnl_Filter.Controls.Add(this.Label10);
			this.pnl_Filter.Controls.Add(this.PictureBox1);
			this.pnl_Filter.Controls.Add(this.cmbo_SalMaliFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_FehrestFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_NoaSanadFltr);
			this.pnl_Filter.Controls.Add(this.txt_CommentFltr);
			this.pnl_Filter.Controls.Add(this.txt_KarfarmaFltr);
			this.pnl_Filter.Controls.Add(this.txt_ProjectFltr);
			this.pnl_Filter.Controls.Add(this.txt_SanadDateFltr);
			this.pnl_Filter.Controls.Add(this.txt_JobNoFltr);
			this.pnl_Filter.Controls.Add(this.txt_SanadNoFltr);
			this.pnl_Filter.Controls.Add(this.txt_BahaFltr);
			this.pnl_Filter.Controls.Add(this.txt_AmaliatFltr);
			this.pnl_Filter.Location = new System.Drawing.Point(1, 4);
			this.pnl_Filter.Name = "pnl_Filter";
			this.pnl_Filter.Size = new System.Drawing.Size(1157, 60);
			this.pnl_Filter.TabIndex = 71;
			this.btn_Filter.BackColor = System.Drawing.Color.WhiteSmoke;
			this.btn_Filter.Enabled = false;
			this.btn_Filter.Font = new System.Drawing.Font("Times New Roman", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.btn_Filter.ForeColor = System.Drawing.Color.Black;
			this.btn_Filter.Image = (System.Drawing.Image)resources.GetObject("btn_Filter.Image");
			this.btn_Filter.Location = new System.Drawing.Point(1116, 0);
			this.btn_Filter.Name = "btn_Filter";
			this.btn_Filter.Size = new System.Drawing.Size(40, 59);
			this.btn_Filter.TabIndex = 148;
			this.btn_Filter.UseVisualStyleBackColor = false;
			this.Label10.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.Label10.BackColor = System.Drawing.Color.White;
			this.Label10.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label10.Location = new System.Drawing.Point(1082, 1);
			this.Label10.Name = "Label10";
			this.Label10.Size = new System.Drawing.Size(35, 58);
			this.Label10.TabIndex = 154;
			this.Label10.Text = "ردیف";
			this.Label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.PictureBox1.Image = (System.Drawing.Image)resources.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new System.Drawing.Point(1, 1);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new System.Drawing.Size(1159, 32);
			this.PictureBox1.TabIndex = 156;
			this.PictureBox1.TabStop = false;
			this.cmbo_SalMaliFltr.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbo_SalMaliFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_SalMaliFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_SalMaliFltr.FormattingEnabled = true;
			this.cmbo_SalMaliFltr.Location = new System.Drawing.Point(976, 37);
			this.cmbo_SalMaliFltr.Name = "cmbo_SalMaliFltr";
			this.cmbo_SalMaliFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_SalMaliFltr.Size = new System.Drawing.Size(45, 26);
			this.cmbo_SalMaliFltr.TabIndex = 155;
			this.cmbo_FehrestFltr.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbo_FehrestFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_FehrestFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_FehrestFltr.FormattingEnabled = true;
			this.cmbo_FehrestFltr.Location = new System.Drawing.Point(1, 37);
			this.cmbo_FehrestFltr.Name = "cmbo_FehrestFltr";
			this.cmbo_FehrestFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_FehrestFltr.Size = new System.Drawing.Size(119, 26);
			this.cmbo_FehrestFltr.TabIndex = 86;
			this.cmbo_NoaSanadFltr.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbo_NoaSanadFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_NoaSanadFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_NoaSanadFltr.FormattingEnabled = true;
			this.cmbo_NoaSanadFltr.Location = new System.Drawing.Point(1022, 37);
			this.cmbo_NoaSanadFltr.Name = "cmbo_NoaSanadFltr";
			this.cmbo_NoaSanadFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_NoaSanadFltr.Size = new System.Drawing.Size(60, 26);
			this.cmbo_NoaSanadFltr.TabIndex = 73;
			this.txt_CommentFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_CommentFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_CommentFltr.Location = new System.Drawing.Point(121, 37);
			this.txt_CommentFltr.Name = "txt_CommentFltr";
			this.txt_CommentFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_CommentFltr.Size = new System.Drawing.Size(149, 26);
			this.txt_CommentFltr.TabIndex = 57;
			this.txt_KarfarmaFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_KarfarmaFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_KarfarmaFltr.Location = new System.Drawing.Point(511, 37);
			this.txt_KarfarmaFltr.Name = "txt_KarfarmaFltr";
			this.txt_KarfarmaFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_KarfarmaFltr.Size = new System.Drawing.Size(149, 26);
			this.txt_KarfarmaFltr.TabIndex = 55;
			this.txt_ProjectFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ProjectFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ProjectFltr.Location = new System.Drawing.Point(661, 37);
			this.txt_ProjectFltr.Name = "txt_ProjectFltr";
			this.txt_ProjectFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ProjectFltr.Size = new System.Drawing.Size(149, 26);
			this.txt_ProjectFltr.TabIndex = 54;
			this.txt_SanadDateFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadDateFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_SanadDateFltr.Location = new System.Drawing.Point(811, 37);
			this.txt_SanadDateFltr.Name = "txt_SanadDateFltr";
			this.txt_SanadDateFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_SanadDateFltr.Size = new System.Drawing.Size(54, 26);
			this.txt_SanadDateFltr.TabIndex = 53;
			this.txt_JobNoFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_JobNoFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_JobNoFltr.Location = new System.Drawing.Point(866, 37);
			this.txt_JobNoFltr.Name = "txt_JobNoFltr";
			this.txt_JobNoFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_JobNoFltr.Size = new System.Drawing.Size(54, 26);
			this.txt_JobNoFltr.TabIndex = 50;
			this.txt_SanadNoFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadNoFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_SanadNoFltr.Location = new System.Drawing.Point(921, 37);
			this.txt_SanadNoFltr.Name = "txt_SanadNoFltr";
			this.txt_SanadNoFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_SanadNoFltr.Size = new System.Drawing.Size(54, 26);
			this.txt_SanadNoFltr.TabIndex = 54;
			this.txt_BahaFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_BahaFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_BahaFltr.Location = new System.Drawing.Point(421, 37);
			this.txt_BahaFltr.Name = "txt_BahaFltr";
			this.txt_BahaFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_BahaFltr.Size = new System.Drawing.Size(89, 26);
			this.txt_BahaFltr.TabIndex = 47;
			this.txt_AmaliatFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_AmaliatFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_AmaliatFltr.Location = new System.Drawing.Point(271, 37);
			this.txt_AmaliatFltr.Name = "txt_AmaliatFltr";
			this.txt_AmaliatFltr.Size = new System.Drawing.Size(149, 26);
			this.txt_AmaliatFltr.TabIndex = 48;
			this.pnl_Asnad.BackColor = System.Drawing.Color.LightSteelBlue;
			this.pnl_Asnad.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnl_Asnad.Controls.Add(this.txt_SanadNo);
			this.pnl_Asnad.Controls.Add(this.txt_Karfarma);
			this.pnl_Asnad.Controls.Add(this.txt_Project);
			this.pnl_Asnad.Controls.Add(this.btn_KarfarmaSearch);
			this.pnl_Asnad.Controls.Add(this.btn_projectSearch);
			this.pnl_Asnad.Controls.Add(this.DateTimePicker1);
			this.pnl_Asnad.Controls.Add(this.txt_SanadYear);
			this.pnl_Asnad.Controls.Add(this.txt_SanadMonth);
			this.pnl_Asnad.Controls.Add(this.txt_SanadDay);
			this.pnl_Asnad.Controls.Add(this.Label16);
			this.pnl_Asnad.Controls.Add(this.Label17);
			this.pnl_Asnad.Controls.Add(this.Label18);
			this.pnl_Asnad.Controls.Add(this.btn_Delete);
			this.pnl_Asnad.Controls.Add(this.btn_OnvanCode);
			this.pnl_Asnad.Controls.Add(this.Btn_Open);
			this.pnl_Asnad.Controls.Add(this.cmbo_Amaliat);
			this.pnl_Asnad.Controls.Add(this.cmbo_OnvanCode);
			this.pnl_Asnad.Controls.Add(this.cmbo_SalMali);
			this.pnl_Asnad.Controls.Add(this.Label5);
			this.pnl_Asnad.Controls.Add(this.lbl_Baha);
			this.pnl_Asnad.Controls.Add(this.btn_Exit);
			this.pnl_Asnad.Controls.Add(this.btn_Copy);
			this.pnl_Asnad.Controls.Add(this.btn_Insert);
			this.pnl_Asnad.Controls.Add(this.Btn_Save);
			this.pnl_Asnad.Controls.Add(this.Panel8);
			this.pnl_Asnad.Controls.Add(this.cmbo_FehrestName);
			this.pnl_Asnad.Controls.Add(this.Label34);
			this.pnl_Asnad.Controls.Add(this.Label32);
			this.pnl_Asnad.Controls.Add(this.cmbo_SanadNoa);
			this.pnl_Asnad.Controls.Add(this.Label9);
			this.pnl_Asnad.Controls.Add(this.txt_JobNo);
			this.pnl_Asnad.Controls.Add(this.txt_Comment);
			this.pnl_Asnad.Controls.Add(this.Label33);
			this.pnl_Asnad.Controls.Add(this.Label8);
			this.pnl_Asnad.Controls.Add(this.Label22);
			this.pnl_Asnad.Controls.Add(this.Label1);
			this.pnl_Asnad.Controls.Add(this.Label2);
			this.pnl_Asnad.Controls.Add(this.Label4);
			this.pnl_Asnad.Controls.Add(this.Label3);
			this.pnl_Asnad.Location = new System.Drawing.Point(1, 498);
			this.pnl_Asnad.Name = "pnl_Asnad";
			this.pnl_Asnad.Size = new System.Drawing.Size(1180, 207);
			this.pnl_Asnad.TabIndex = 66;
			this.txt_SanadNo.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadNo.Location = new System.Drawing.Point(991, 34);
			this.txt_SanadNo.Name = "txt_SanadNo";
			this.txt_SanadNo.Size = new System.Drawing.Size(100, 26);
			this.txt_SanadNo.TabIndex = 5;
			this.txt_Karfarma.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_Karfarma.Location = new System.Drawing.Point(674, 112);
			this.txt_Karfarma.Name = "txt_Karfarma";
			this.txt_Karfarma.Size = new System.Drawing.Size(417, 26);
			this.txt_Karfarma.TabIndex = 9;
			this.txt_Project.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_Project.Location = new System.Drawing.Point(674, 86);
			this.txt_Project.Name = "txt_Project";
			this.txt_Project.Size = new System.Drawing.Size(417, 26);
			this.txt_Project.TabIndex = 8;
			this.btn_KarfarmaSearch.Image = (System.Drawing.Image)resources.GetObject("btn_KarfarmaSearch.Image");
			this.btn_KarfarmaSearch.Location = new System.Drawing.Point(648, 112);
			this.btn_KarfarmaSearch.Name = "btn_KarfarmaSearch";
			this.btn_KarfarmaSearch.Size = new System.Drawing.Size(26, 25);
			this.btn_KarfarmaSearch.TabIndex = 160;
			this.btn_KarfarmaSearch.UseVisualStyleBackColor = true;
			this.btn_projectSearch.Image = (System.Drawing.Image)resources.GetObject("btn_projectSearch.Image");
			this.btn_projectSearch.Location = new System.Drawing.Point(648, 86);
			this.btn_projectSearch.Name = "btn_projectSearch";
			this.btn_projectSearch.Size = new System.Drawing.Size(26, 25);
			this.btn_projectSearch.TabIndex = 159;
			this.btn_projectSearch.UseVisualStyleBackColor = true;
			this.DateTimePicker1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
			this.DateTimePicker1.CalendarFont = new System.Drawing.Font("Times New Roman", 12f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
			this.DateTimePicker1.CustomFormat = "dd/MM/yyyy";
			this.DateTimePicker1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.DateTimePicker1.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
			this.DateTimePicker1.Location = new System.Drawing.Point(757, 9);
			this.DateTimePicker1.Name = "DateTimePicker1";
			this.DateTimePicker1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.DateTimePicker1.RightToLeftLayout = true;
			this.DateTimePicker1.Size = new System.Drawing.Size(0, 20);
			this.DateTimePicker1.TabIndex = 158;
			this.txt_SanadYear.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadYear.Location = new System.Drawing.Point(710, 9);
			this.txt_SanadYear.Name = "txt_SanadYear";
			this.txt_SanadYear.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_SanadYear.Size = new System.Drawing.Size(40, 26);
			this.txt_SanadYear.TabIndex = 4;
			this.txt_SanadMonth.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadMonth.Location = new System.Drawing.Point(759, 9);
			this.txt_SanadMonth.Name = "txt_SanadMonth";
			this.txt_SanadMonth.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_SanadMonth.Size = new System.Drawing.Size(40, 26);
			this.txt_SanadMonth.TabIndex = 3;
			this.txt_SanadDay.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_SanadDay.Location = new System.Drawing.Point(809, 8);
			this.txt_SanadDay.Name = "txt_SanadDay";
			this.txt_SanadDay.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_SanadDay.Size = new System.Drawing.Size(40, 26);
			this.txt_SanadDay.TabIndex = 2;
			this.Label16.AutoSize = true;
			this.Label16.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.Label16.Location = new System.Drawing.Point(799, 10);
			this.Label16.Name = "Label16";
			this.Label16.Size = new System.Drawing.Size(13, 16);
			this.Label16.TabIndex = 154;
			this.Label16.Text = "/";
			this.Label17.AutoSize = true;
			this.Label17.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.Label17.Location = new System.Drawing.Point(749, 10);
			this.Label17.Name = "Label17";
			this.Label17.Size = new System.Drawing.Size(13, 16);
			this.Label17.TabIndex = 153;
			this.Label17.Text = "/";
			this.Label18.AutoSize = true;
			this.Label18.Location = new System.Drawing.Point(848, 12);
			this.Label18.Name = "Label18";
			this.Label18.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label18.Size = new System.Drawing.Size(38, 13);
			this.Label18.TabIndex = 152;
			this.Label18.Text = ": تاریخ";
			this.btn_Delete.Location = new System.Drawing.Point(220, 171);
			this.btn_Delete.Name = "btn_Delete";
			this.btn_Delete.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Delete.Size = new System.Drawing.Size(90, 30);
			this.btn_Delete.TabIndex = 19;
			this.btn_Delete.Text = "(Del) حذف";
			this.btn_Delete.UseVisualStyleBackColor = true;
			this.btn_OnvanCode.Image = (System.Drawing.Image)resources.GetObject("btn_OnvanCode.Image");
			this.btn_OnvanCode.Location = new System.Drawing.Point(21, 5);
			this.btn_OnvanCode.Name = "btn_OnvanCode";
			this.btn_OnvanCode.Size = new System.Drawing.Size(28, 26);
			this.btn_OnvanCode.TabIndex = 150;
			this.btn_OnvanCode.UseVisualStyleBackColor = true;
			this.Btn_Open.Location = new System.Drawing.Point(864, 171);
			this.Btn_Open.Name = "Btn_Open";
			this.Btn_Open.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Open.Size = new System.Drawing.Size(90, 30);
			this.Btn_Open.TabIndex = 16;
			this.Btn_Open.Text = "(DblClk) نمایش";
			this.Btn_Open.UseVisualStyleBackColor = true;
			this.cmbo_Amaliat.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_Amaliat.FormattingEnabled = true;
			this.cmbo_Amaliat.Location = new System.Drawing.Point(674, 138);
			this.cmbo_Amaliat.Name = "cmbo_Amaliat";
			this.cmbo_Amaliat.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_Amaliat.Size = new System.Drawing.Size(417, 26);
			this.cmbo_Amaliat.TabIndex = 10;
			this.cmbo_OnvanCode.Enabled = false;
			this.cmbo_OnvanCode.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.cmbo_OnvanCode.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_OnvanCode.FormattingEnabled = true;
			this.cmbo_OnvanCode.Location = new System.Drawing.Point(48, 6);
			this.cmbo_OnvanCode.Name = "cmbo_OnvanCode";
			this.cmbo_OnvanCode.Size = new System.Drawing.Size(82, 26);
			this.cmbo_OnvanCode.TabIndex = 12;
			this.cmbo_SalMali.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_SalMali.FormattingEnabled = true;
			this.cmbo_SalMali.Location = new System.Drawing.Point(991, 8);
			this.cmbo_SalMali.Name = "cmbo_SalMali";
			this.cmbo_SalMali.Size = new System.Drawing.Size(100, 26);
			this.cmbo_SalMali.TabIndex = 1;
			this.Label5.AutoSize = true;
			this.Label5.Location = new System.Drawing.Point(130, 12);
			this.Label5.Name = "Label5";
			this.Label5.Size = new System.Drawing.Size(73, 13);
			this.Label5.TabIndex = 123;
			this.Label5.Text = " کد مشخصات :";
			this.lbl_Baha.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_Baha.Location = new System.Drawing.Point(681, 57);
			this.lbl_Baha.Name = "lbl_Baha";
			this.lbl_Baha.Size = new System.Drawing.Size(172, 20);
			this.lbl_Baha.TabIndex = 121;
			this.lbl_Baha.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.btn_Exit.Location = new System.Drawing.Point(15, 171);
			this.btn_Exit.Name = "btn_Exit";
			this.btn_Exit.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Exit.Size = new System.Drawing.Size(100, 30);
			this.btn_Exit.TabIndex = 15;
			this.btn_Exit.Text = "(Esc) بازگشت ";
			this.btn_Exit.UseVisualStyleBackColor = true;
			this.btn_Copy.Location = new System.Drawing.Point(431, 171);
			this.btn_Copy.Name = "btn_Copy";
			this.btn_Copy.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Copy.Size = new System.Drawing.Size(90, 30);
			this.btn_Copy.TabIndex = 18;
			this.btn_Copy.Text = "(Ctrl + C) کپی ";
			this.btn_Copy.UseVisualStyleBackColor = true;
			this.btn_Insert.Location = new System.Drawing.Point(656, 171);
			this.btn_Insert.Name = "btn_Insert";
			this.btn_Insert.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Insert.Size = new System.Drawing.Size(90, 30);
			this.btn_Insert.TabIndex = 17;
			this.btn_Insert.Text = "(Insert) جدید  ";
			this.btn_Insert.UseVisualStyleBackColor = true;
			this.Btn_Save.Location = new System.Drawing.Point(1059, 171);
			this.Btn_Save.Name = "Btn_Save";
			this.Btn_Save.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Save.Size = new System.Drawing.Size(90, 30);
			this.Btn_Save.TabIndex = 14;
			this.Btn_Save.Text = "(F2) ذخیره ";
			this.Btn_Save.UseVisualStyleBackColor = true;
			this.Panel8.Controls.Add(this.lbl_SanadBakhshCode);
			this.Panel8.Controls.Add(this.lbl_SanadZaribComment2);
			this.Panel8.Controls.Add(this.lbl_SanadZaribComment1);
			this.Panel8.Controls.Add(this.lbl_SanadZarib2);
			this.Panel8.Controls.Add(this.lbl_SanadZarib1);
			this.Panel8.Controls.Add(this.lbl_SanadBakhsh);
			this.Panel8.Controls.Add(this.lbl_SanadShahr);
			this.Panel8.Controls.Add(this.lbl_SanadOstan);
			this.Panel8.Controls.Add(this.Label39);
			this.Panel8.Controls.Add(this.Label40);
			this.Panel8.Controls.Add(this.Label41);
			this.Panel8.Controls.Add(this.Label42);
			this.Panel8.Location = new System.Drawing.Point(4, 36);
			this.Panel8.Name = "Panel8";
			this.Panel8.Size = new System.Drawing.Size(618, 77);
			this.Panel8.TabIndex = 85;
			this.lbl_SanadBakhshCode.AutoSize = true;
			this.lbl_SanadBakhshCode.Location = new System.Drawing.Point(310, 21);
			this.lbl_SanadBakhshCode.Name = "lbl_SanadBakhshCode";
			this.lbl_SanadBakhshCode.Size = new System.Drawing.Size(0, 13);
			this.lbl_SanadBakhshCode.TabIndex = 108;
			this.lbl_SanadBakhshCode.Visible = false;
			this.lbl_SanadZaribComment2.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZaribComment2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZaribComment2.Location = new System.Drawing.Point(12, 41);
			this.lbl_SanadZaribComment2.Name = "lbl_SanadZaribComment2";
			this.lbl_SanadZaribComment2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZaribComment2.Size = new System.Drawing.Size(274, 20);
			this.lbl_SanadZaribComment2.TabIndex = 107;
			this.lbl_SanadZaribComment2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadZaribComment1.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZaribComment1.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZaribComment1.Location = new System.Drawing.Point(12, 18);
			this.lbl_SanadZaribComment1.Name = "lbl_SanadZaribComment1";
			this.lbl_SanadZaribComment1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZaribComment1.Size = new System.Drawing.Size(274, 20);
			this.lbl_SanadZaribComment1.TabIndex = 106;
			this.lbl_SanadZaribComment1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadZarib2.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZarib2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZarib2.Location = new System.Drawing.Point(290, 41);
			this.lbl_SanadZarib2.Name = "lbl_SanadZarib2";
			this.lbl_SanadZarib2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZarib2.Size = new System.Drawing.Size(43, 20);
			this.lbl_SanadZarib2.TabIndex = 105;
			this.lbl_SanadZarib2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.lbl_SanadZarib1.BackColor = System.Drawing.Color.White;
			this.lbl_SanadZarib1.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadZarib1.Location = new System.Drawing.Point(290, 18);
			this.lbl_SanadZarib1.Name = "lbl_SanadZarib1";
			this.lbl_SanadZarib1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadZarib1.Size = new System.Drawing.Size(43, 20);
			this.lbl_SanadZarib1.TabIndex = 104;
			this.lbl_SanadZarib1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.lbl_SanadBakhsh.BackColor = System.Drawing.Color.White;
			this.lbl_SanadBakhsh.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadBakhsh.Location = new System.Drawing.Point(446, 52);
			this.lbl_SanadBakhsh.Name = "lbl_SanadBakhsh";
			this.lbl_SanadBakhsh.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadBakhsh.Size = new System.Drawing.Size(112, 21);
			this.lbl_SanadBakhsh.TabIndex = 103;
			this.lbl_SanadBakhsh.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadShahr.BackColor = System.Drawing.Color.White;
			this.lbl_SanadShahr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadShahr.Location = new System.Drawing.Point(446, 28);
			this.lbl_SanadShahr.Name = "lbl_SanadShahr";
			this.lbl_SanadShahr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadShahr.Size = new System.Drawing.Size(112, 21);
			this.lbl_SanadShahr.TabIndex = 102;
			this.lbl_SanadShahr.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_SanadOstan.BackColor = System.Drawing.Color.White;
			this.lbl_SanadOstan.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_SanadOstan.Location = new System.Drawing.Point(446, 4);
			this.lbl_SanadOstan.Name = "lbl_SanadOstan";
			this.lbl_SanadOstan.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_SanadOstan.Size = new System.Drawing.Size(112, 21);
			this.lbl_SanadOstan.TabIndex = 14;
			this.lbl_SanadOstan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Label39.Location = new System.Drawing.Point(329, 34);
			this.Label39.Name = "Label39";
			this.Label39.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label39.Size = new System.Drawing.Size(91, 27);
			this.Label39.TabIndex = 93;
			this.Label39.Text = " :ضریب منطقه ای";
			this.Label40.AutoSize = true;
			this.Label40.Location = new System.Drawing.Point(557, 10);
			this.Label40.Name = "Label40";
			this.Label40.Size = new System.Drawing.Size(40, 13);
			this.Label40.TabIndex = 92;
			this.Label40.Text = "استان :";
			this.Label41.AutoSize = true;
			this.Label41.Location = new System.Drawing.Point(557, 33);
			this.Label41.Name = "Label41";
			this.Label41.Size = new System.Drawing.Size(60, 13);
			this.Label41.TabIndex = 91;
			this.Label41.Text = " شهرستان :";
			this.Label42.AutoSize = true;
			this.Label42.Location = new System.Drawing.Point(558, 54);
			this.Label42.Name = "Label42";
			this.Label42.Size = new System.Drawing.Size(36, 13);
			this.Label42.TabIndex = 90;
			this.Label42.Text = " بخش :";
			this.cmbo_FehrestName.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.cmbo_FehrestName.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_FehrestName.FormattingEnabled = true;
			this.cmbo_FehrestName.Location = new System.Drawing.Point(263, 6);
			this.cmbo_FehrestName.Name = "cmbo_FehrestName";
			this.cmbo_FehrestName.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_FehrestName.Size = new System.Drawing.Size(300, 26);
			this.cmbo_FehrestName.TabIndex = 11;
			this.Label34.AutoSize = true;
			this.Label34.Location = new System.Drawing.Point(1090, 12);
			this.Label34.Name = "Label34";
			this.Label34.Size = new System.Drawing.Size(61, 13);
			this.Label34.TabIndex = 78;
			this.Label34.Text = " سال مالی :";
			this.Label32.AccessibleRole = System.Windows.Forms.AccessibleRole.None;
			this.Label32.AutoSize = true;
			this.Label32.Location = new System.Drawing.Point(847, 38);
			this.Label32.Name = "Label32";
			this.Label32.Size = new System.Drawing.Size(54, 13);
			this.Label32.TabIndex = 77;
			this.Label32.Text = " نوع سند :";
			this.cmbo_SanadNoa.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbo_SanadNoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
			this.cmbo_SanadNoa.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_SanadNoa.FormattingEnabled = true;
			this.cmbo_SanadNoa.Location = new System.Drawing.Point(711, 36);
			this.cmbo_SanadNoa.Name = "cmbo_SanadNoa";
			this.cmbo_SanadNoa.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_SanadNoa.Size = new System.Drawing.Size(136, 26);
			this.cmbo_SanadNoa.TabIndex = 6;
			this.Label9.AutoSize = true;
			this.Label9.Location = new System.Drawing.Point(855, 61);
			this.Label9.Name = "Label9";
			this.Label9.Size = new System.Drawing.Size(35, 13);
			this.Label9.TabIndex = 60;
			this.Label9.Text = " مبلغ :";
			this.txt_JobNo.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_JobNo.Location = new System.Drawing.Point(991, 60);
			this.txt_JobNo.Name = "txt_JobNo";
			this.txt_JobNo.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_JobNo.Size = new System.Drawing.Size(100, 26);
			this.txt_JobNo.TabIndex = 7;
			this.txt_Comment.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_Comment.Location = new System.Drawing.Point(14, 125);
			this.txt_Comment.Name = "txt_Comment";
			this.txt_Comment.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_Comment.Size = new System.Drawing.Size(548, 26);
			this.txt_Comment.TabIndex = 13;
			this.Label33.AutoSize = true;
			this.Label33.Location = new System.Drawing.Point(560, 131);
			this.Label33.Name = "Label33";
			this.Label33.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label33.Size = new System.Drawing.Size(55, 13);
			this.Label33.TabIndex = 50;
			this.Label33.Text = ": توضیحات";
			this.Label8.AutoSize = true;
			this.Label8.Location = new System.Drawing.Point(562, 13);
			this.Label8.Name = "Label8";
			this.Label8.Size = new System.Drawing.Size(67, 13);
			this.Label8.TabIndex = 47;
			this.Label8.Text = " فهرست بها :";
			this.Label22.AutoSize = true;
			this.Label22.Location = new System.Drawing.Point(1091, 38);
			this.Label22.Name = "Label22";
			this.Label22.Size = new System.Drawing.Size(66, 13);
			this.Label22.TabIndex = 36;
			this.Label22.Text = " شماره سند :";
			this.Label1.AutoSize = true;
			this.Label1.Location = new System.Drawing.Point(1092, 64);
			this.Label1.Name = "Label1";
			this.Label1.Size = new System.Drawing.Size(61, 13);
			this.Label1.TabIndex = 0;
			this.Label1.Text = "شماره کار :";
			this.Label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Label2.AutoSize = true;
			this.Label2.Location = new System.Drawing.Point(1091, 93);
			this.Label2.Name = "Label2";
			this.Label2.Size = new System.Drawing.Size(58, 13);
			this.Label2.TabIndex = 100;
			this.Label2.Text = " نام پروژه :";
			this.Label4.AutoSize = true;
			this.Label4.Location = new System.Drawing.Point(1090, 141);
			this.Label4.Name = "Label4";
			this.Label4.Size = new System.Drawing.Size(73, 13);
			this.Label4.TabIndex = 102;
			this.Label4.Text = "  موضوع سند :";
			this.Label3.AutoSize = true;
			this.Label3.Location = new System.Drawing.Point(1089, 120);
			this.Label3.Name = "Label3";
			this.Label3.Size = new System.Drawing.Size(68, 13);
			this.Label3.TabIndex = 101;
			this.Label3.Text = " نام کارفرما :";
			this.Panel1.BackColor = System.Drawing.SystemColors.Control;
			this.Panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.Panel1.Controls.Add(this.lbl_AsnadSum);
			this.Panel1.Controls.Add(this.lbl_AsnadNum);
			this.Panel1.Controls.Add(this.Label26);
			this.Panel1.Controls.Add(this.Label28);
			this.Panel1.Location = new System.Drawing.Point(1, 466);
			this.Panel1.Name = "Panel1";
			this.Panel1.Size = new System.Drawing.Size(1180, 28);
			this.Panel1.TabIndex = 65;
			this.lbl_AsnadSum.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_AsnadSum.ForeColor = System.Drawing.Color.Black;
			this.lbl_AsnadSum.Location = new System.Drawing.Point(417, 4);
			this.lbl_AsnadSum.Name = "lbl_AsnadSum";
			this.lbl_AsnadSum.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_AsnadSum.Size = new System.Drawing.Size(149, 20);
			this.lbl_AsnadSum.TabIndex = 46;
			this.lbl_AsnadSum.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.lbl_AsnadNum.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_AsnadNum.ForeColor = System.Drawing.Color.Black;
			this.lbl_AsnadNum.Location = new System.Drawing.Point(833, 3);
			this.lbl_AsnadNum.Name = "lbl_AsnadNum";
			this.lbl_AsnadNum.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.lbl_AsnadNum.Size = new System.Drawing.Size(118, 20);
			this.lbl_AsnadNum.TabIndex = 44;
			this.lbl_AsnadNum.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.Label26.AutoSize = true;
			this.Label26.ForeColor = System.Drawing.Color.Black;
			this.Label26.Location = new System.Drawing.Point(570, 6);
			this.Label26.Name = "Label26";
			this.Label26.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label26.Size = new System.Drawing.Size(82, 13);
			this.Label26.TabIndex = 42;
			this.Label26.Text = ": جمع مبلغ اسناد";
			this.Label28.AutoSize = true;
			this.Label28.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.Label28.ForeColor = System.Drawing.Color.Black;
			this.Label28.Location = new System.Drawing.Point(956, 5);
			this.Label28.Name = "Label28";
			this.Label28.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label28.Size = new System.Drawing.Size(64, 13);
			this.Label28.TabIndex = 40;
			this.Label28.Text = ": تعداد اسناد";
			this.dtg_AsnadList.AllowUserToAddRows = false;
			this.dtg_AsnadList.AllowUserToDeleteRows = false;
			this.dtg_AsnadList.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
			dataGridViewCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = System.Drawing.SystemColors.Control;
			dataGridViewCellStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			dataGridViewCellStyle.ForeColor = System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
			this.dtg_AsnadList.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.dtg_AsnadList.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			dataGridViewCellStyle2.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dtg_AsnadList.DefaultCellStyle = dataGridViewCellStyle2;
			this.dtg_AsnadList.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.dtg_AsnadList.Location = new System.Drawing.Point(1, 46);
			this.dtg_AsnadList.MultiSelect = false;
			this.dtg_AsnadList.Name = "dtg_AsnadList";
			this.dtg_AsnadList.ReadOnly = true;
			this.dtg_AsnadList.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			dataGridViewCellStyle3.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dtg_AsnadList.RowsDefaultCellStyle = dataGridViewCellStyle3;
			this.dtg_AsnadList.RowTemplate.Height = 44;
			this.dtg_AsnadList.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dtg_AsnadList.Size = new System.Drawing.Size(1180, 419);
			this.dtg_AsnadList.TabIndex = 12;
			this.txt_Roonevesht.Location = new System.Drawing.Point(882, 130);
			this.txt_Roonevesht.Name = "txt_Roonevesht";
			this.txt_Roonevesht.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_Roonevesht.Size = new System.Drawing.Size(560, 20);
			this.txt_Roonevesht.TabIndex = 79;
			this.lbl_User.AutoSize = true;
			this.lbl_User.BackColor = System.Drawing.Color.White;
			this.lbl_User.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
			this.lbl_User.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.lbl_User.Location = new System.Drawing.Point(197, 217);
			this.lbl_User.Name = "lbl_User";
			this.lbl_User.Size = new System.Drawing.Size(74, 26);
			this.lbl_User.TabIndex = 161;
			this.lbl_User.Text = "Label6";
			this.lbl_User.Visible = false;
			this.chk_SabtNashode.AutoSize = true;
			this.chk_SabtNashode.Location = new System.Drawing.Point(1163, 47);
			this.chk_SabtNashode.Name = "chk_SabtNashode";
			this.chk_SabtNashode.Size = new System.Drawing.Size(15, 14);
			this.chk_SabtNashode.TabIndex = 162;
			this.chk_SabtNashode.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.chk_SabtNashode.UseVisualStyleBackColor = true;
			this.Label6.BackColor = System.Drawing.Color.WhiteSmoke;
			this.Label6.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label6.Font = new System.Drawing.Font("B Titr", 6.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.Label6.Location = new System.Drawing.Point(1156, 4);
			this.Label6.Name = "Label6";
			this.Label6.Size = new System.Drawing.Size(26, 60);
			this.Label6.TabIndex = 163;
			this.Label6.Text = "ثبت نشده";
			base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.AutoScroll = true;
			this.BackColor = System.Drawing.Color.LightSteelBlue;
			base.ClientSize = new System.Drawing.Size(1184, 711);
			base.ControlBox = false;
			base.Controls.Add(this.chk_SabtNashode);
			base.Controls.Add(this.Label6);
			base.Controls.Add(this.lbl_User);
			base.Controls.Add(this.Panel1);
			base.Controls.Add(this.pnl_Filter);
			base.Controls.Add(this.pnl_Asnad);
			base.Controls.Add(this.dtg_AsnadList);
			base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			base.Name = "Frm_AsnadList";
			this.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.RightToLeftLayout = true;
			base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "لیست اسناد";
			this.pnl_Filter.ResumeLayout(false);
			this.pnl_Filter.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.pnl_Asnad.ResumeLayout(false);
			this.pnl_Asnad.PerformLayout();
			this.Panel8.ResumeLayout(false);
			this.Panel8.PerformLayout();
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_AsnadList).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();

            this.txt_BahaFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_BahaFltr_KeyDown);
            this.txt_AmaliatFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_AmaliatFltr_KeyDown);
            this.txt_Comment.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_Comment_KeyDown);
            this.txt_Comment.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_Comment_KeyUp);
            this.txt_Comment.TextChanged += new System.EventHandler(this.txt_Comment_TextChanged);
            this.dtg_AsnadList.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Asnad_CellClick);
            this.dtg_AsnadList.CellContentDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_AsnadList_CellContentDoubleClick);
            this.dtg_AsnadList.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_AsnadList_CellDoubleClick);
            this.dtg_AsnadList.Click += new System.EventHandler(this.dtg_AsnadList_Click);
            this.dtg_AsnadList.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dtg_AsnadList_KeyDown);
            this.dtg_AsnadList.SelectionChanged += new System.EventHandler(this.dtg_Asnad_SelectionChanged);
            this.dtg_AsnadList.MouseDown += new System.Windows.Forms.MouseEventHandler(this.dtg_AsnadList_MouseDown);
            this.dtg_AsnadList.CellMouseDown += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dtg_AsnadList_CellMouseDown);
            this.dtg_AsnadList.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_AsnadList_CellContentClick);
            this.dtg_AsnadList.MouseWheel += new System.Windows.Forms.MouseEventHandler(this.dtg_AsnadList_MouseWheel);
            this.txt_JobNo.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_JobNo_KeyDown);
            this.txt_JobNo.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_JobNo_KeyUp);
            this.txt_JobNo.TextChanged += new System.EventHandler(this.txt_JobNo_TextChanged);
            this.txt_SanadNoFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_SanadNoFltr_KeyDown);
            this.txt_JobNoFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_JobNoFltr_KeyDown);
            this.txt_KarfarmaFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_KarfarmaFltr_KeyDown);
            this.txt_ProjectFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ProjectFltr_KeyDown);
            this.txt_ProjectFltr.TextChanged += new System.EventHandler(this.txt_ProjectFltr_TextChanged);
            this.txt_SanadDateFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_SanadDateFltr_KeyDown);
            this.txt_CommentFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_CommentFltr_KeyDown);
            this.cmbo_SanadNoa.GotFocus += new System.EventHandler(this.cmbo_SanadNoa_GotFocus);
            this.cmbo_SanadNoa.KeyUp += new System.Windows.Forms.KeyEventHandler(this.cmbo_NoaSanad_KeyUp);
            this.cmbo_SanadNoa.Leave += new System.EventHandler(this.cmbo_SanadNoa_Leave);
            this.cmbo_SanadNoa.SelectedIndexChanged += new System.EventHandler(this.cmbo_NoaSanad_SelectedIndexChanged);
            this.cmbo_SanadNoa.TextChanged += new System.EventHandler(this.cmbo_NoaSanad_TextChanged);
            this.cmbo_NoaSanadFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_NoaSanadFltr_SelectedIndexChanged);
            this.cmbo_FehrestName.GotFocus += new System.EventHandler(this.cmbo_FehrestName_GotFocus);
            this.cmbo_FehrestName.TextChanged += new System.EventHandler(this.cmbo_FehrestName_TextChanged);
            this.cmbo_FehrestName.SelectedIndexChanged += new System.EventHandler(this.cmbo_FehrestName_SelectedIndexChanged);
            this.cmbo_FehrestName.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cmbo_FehrestName_KeyDown);
            this.Btn_Save.Click += new System.EventHandler(this.Btn_Save_Click);
            this.Btn_Save.KeyDown += new System.Windows.Forms.KeyEventHandler(this.Btn_Save_KeyDown);
            this.cmbo_FehrestFltr.GotFocus += new System.EventHandler(this.cmbo_FehrestFltr_GotFocus);
            this.cmbo_FehrestFltr.Leave += new System.EventHandler(this.cmbo_FehrestFltr_Leave);
            this.cmbo_FehrestFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_FehrestFltr_SelectedIndexChanged);
            this.btn_Exit.Click += new System.EventHandler(this.btn_Exit_Click);
            this.btn_Copy.Click += new System.EventHandler(this.btn_copy_Click);
            this.btn_Delete.Click += new System.EventHandler(this.btn_Delete_Click);
            this.btn_Insert.Click += new System.EventHandler(this.btn_Insert_Click);
            this.lbl_Baha.TextChanged += new System.EventHandler(this.lbl_Baha_TextChanged);
            this.cmbo_SalMali.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cmbo_SalMali_KeyDown);
            this.cmbo_SalMali.TextChanged += new System.EventHandler(this.cmbo_SalMali_TextChanged);
            this.cmbo_SalMali.KeyUp += new System.Windows.Forms.KeyEventHandler(this.cmbo_SalMali_KeyUp);
            this.cmbo_SalMali.Leave += new System.EventHandler(this.cmbo_SalMali_Leave);
            this.cmbo_SalMali.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.cmbo_SalMali_KeyPress);
            this.cmbo_SalMali.SelectedIndexChanged += new System.EventHandler(this.cmbo_SalMali_SelectedIndexChanged);
            this.cmbo_OnvanCode.GotFocus += new System.EventHandler(this.cmbo_OnvanCode_GotFocus);
            this.cmbo_OnvanCode.HelpRequested += new System.Windows.Forms.HelpEventHandler(this.cmbo_OnvanCode_HelpRequested);
            this.cmbo_OnvanCode.KeyUp += new System.Windows.Forms.KeyEventHandler(this.cmbo_OnvanCode_KeyUp);
            this.cmbo_OnvanCode.Leave += new System.EventHandler(this.cmbo_OnvanCode_Leave);
            this.cmbo_OnvanCode.TextChanged += new System.EventHandler(this.cmbo_OnvanCode_TextChanged);
            this.cmbo_OnvanCode.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.cmbo_OnvanCode_KeyPress);
            this.cmbo_OnvanCode.SelectedIndexChanged += new System.EventHandler(this.cmbo_OnvanCode_SelectedIndexChanged);
            this.cmbo_OnvanCode.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cmbo_OnvanCode_KeyDown);
            this.cmbo_Amaliat.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cmbo_Amaliat_KeyDown);
            this.cmbo_Amaliat.Leave += new System.EventHandler(this.cmbo_Amaliat_Leave);
            this.cmbo_Amaliat.TextChanged += new System.EventHandler(this.cmbo_Amaliat_TextChanged);
            this.cmbo_Amaliat.KeyUp += new System.Windows.Forms.KeyEventHandler(this.cmbo_Amaliat_KeyUp);
            this.cmbo_Amaliat.SelectedIndexChanged += new System.EventHandler(this.cmbo_Amaliat_SelectedIndexChanged);
            this.Btn_Open.Click += new System.EventHandler(this.Btn_Open_Click);
            this.btn_OnvanCode.Click += new System.EventHandler(this.btn_Anavin_Click);
            this.cmbo_SalMaliFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_SalMaliFltr_SelectedIndexChanged);
            this.cmbo_SalMaliFltr.TextChanged += new System.EventHandler(this.cmbo_SalMaliFltr_TextChanged);
            this.btn_projectSearch.Click += new System.EventHandler(this.btn_projectSearch_Click);
            this.btn_KarfarmaSearch.Click += new System.EventHandler(this.btn_KarfarmaSearch_Click);
            this.txt_Project.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_Project_KeyDown);
            this.txt_Project.Leave += new System.EventHandler(this.txt_Project_Leave);
            this.txt_Project.TextChanged += new System.EventHandler(this.txt_Project_TextChanged);
            this.txt_Project.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_Project_KeyUp);
            this.txt_Karfarma.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_Karfarma_KeyDown);
            this.txt_Karfarma.KeyUp += new System.Windows.Forms.KeyEventHandler(this.txt_Karfarma_KeyUp);
            this.txt_Karfarma.Leave += new System.EventHandler(this.txt_Karfarma_Leave);
            this.txt_Karfarma.TextChanged += new System.EventHandler(this.txt_Karfarma_TextChanged);
            this.btn_Filter.Click += new System.EventHandler(this.btn_Filter_Click);
            this.txt_SanadNo.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_SanadNo_KeyDown);
            this.txt_SanadNo.TextChanged += new System.EventHandler(this.txt_SanadNo_TextChanged_1);
            this.chk_SabtNashode.CheckedChanged += new System.EventHandler(this.chk_SabtNashode_CheckedChanged);
        }
    }
}
