using System;
using System.Windows.Forms;
using System.Drawing;
using System.ComponentModel;

namespace GeoBaha
{
    partial class Frm_FehrestDetail_New
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // Component declarations

        // Controls

        // Button
        private System.Windows.Forms.Button Btn_Copy;
        private System.Windows.Forms.Button Btn_Exit;
        private System.Windows.Forms.Button Btn_Insert;
        private System.Windows.Forms.Button Btn_Save;
        private System.Windows.Forms.Button btn_CopyItem;
        private System.Windows.Forms.Button btn_Delete;
        private System.Windows.Forms.Button btn_DeleteItem;
        private System.Windows.Forms.Button btn_ExitItem;
        private System.Windows.Forms.Button btn_Filter;
        private System.Windows.Forms.Button btn_GroupSearch;
        private System.Windows.Forms.Button btn_InsertItem;
        private System.Windows.Forms.Button btn_SaveItem;
        private System.Windows.Forms.Button btn_VahedSearch;

        // ComboBox
        private System.Windows.Forms.ComboBox cmbo_Fehrest;
        private System.Windows.Forms.ComboBox cmbo_FehrestItem;
        private System.Windows.Forms.ComboBox cmbo_Group;
        private System.Windows.Forms.ComboBox cmbo_GroupFltr;
        private System.Windows.Forms.ComboBox cmbo_ItemFasl;
        private System.Windows.Forms.ComboBox cmbo_ItemFaslFltr;
        private System.Windows.Forms.ComboBox cmbo_ItemNoa;
        private System.Windows.Forms.ComboBox cmbo_ItemNoaFltr;
        private System.Windows.Forms.ComboBox cmbo_ItemVahedSharh;
        private System.Windows.Forms.ComboBox cmbo_ItemVahedSharhFltr;
        private System.Windows.Forms.ComboBox cmbo_ZaribCode;

        // DataGridView
        private System.Windows.Forms.DataGridView dtg_Fosool;
        private System.Windows.Forms.DataGridView dtg_Item;

        // Label
        private System.Windows.Forms.Label Label1;
        private System.Windows.Forms.Label Label10;
        private System.Windows.Forms.Label Label2;
        private System.Windows.Forms.Label Label21;
        private System.Windows.Forms.Label Label3;
        private System.Windows.Forms.Label Label30;
        private System.Windows.Forms.Label Label31;
        private System.Windows.Forms.Label Label35;
        private System.Windows.Forms.Label Label38;
        private System.Windows.Forms.Label Label4;
        private System.Windows.Forms.Label Label43;
        private System.Windows.Forms.Label Label5;
        private System.Windows.Forms.Label Label7;

        // Panel
        private System.Windows.Forms.Panel pnl_Fasl;
        private System.Windows.Forms.Panel pnl_Filter;
        private System.Windows.Forms.Panel pnl_Item;

        // PictureBox
        private System.Windows.Forms.PictureBox PictureBox1;

        // TabControl
        private System.Windows.Forms.TabControl tab_Fosool;

        // TabPage
        private System.Windows.Forms.TabPage tbp_Fosool;
        private System.Windows.Forms.TabPage tbp_Item;

        // TextBox
        private System.Windows.Forms.TextBox txt_FaslCode;
        private System.Windows.Forms.TextBox txt_FaslComment;
        private System.Windows.Forms.TextBox txt_ItemBahavahed;
        private System.Windows.Forms.TextBox txt_ItemBahavahedFltr;
        private System.Windows.Forms.TextBox txt_ItemDarsad;
        private System.Windows.Forms.TextBox txt_ItemNo;
        private System.Windows.Forms.TextBox txt_ItemNoFltr;
        private System.Windows.Forms.TextBox txt_ItemSharh;
        private System.Windows.Forms.TextBox txt_ItemSharhFltr;
        private System.Windows.Forms.TextBox txt_ZaribComment;

        private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(GeoBaha.Frm_FehrestDetail));
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
			System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
			this.tbp_Item = new System.Windows.Forms.TabPage();
			this.pnl_Filter = new System.Windows.Forms.Panel();
			this.Label10 = new System.Windows.Forms.Label();
			this.cmbo_GroupFltr = new System.Windows.Forms.ComboBox();
			this.cmbo_ItemVahedSharhFltr = new System.Windows.Forms.ComboBox();
			this.cmbo_ItemFaslFltr = new System.Windows.Forms.ComboBox();
			this.txt_ItemNoFltr = new System.Windows.Forms.TextBox();
			this.cmbo_ItemNoaFltr = new System.Windows.Forms.ComboBox();
			this.txt_ItemBahavahedFltr = new System.Windows.Forms.TextBox();
			this.txt_ItemSharhFltr = new System.Windows.Forms.TextBox();
			this.btn_Filter = new System.Windows.Forms.Button();
			this.PictureBox1 = new System.Windows.Forms.PictureBox();
			this.pnl_Item = new System.Windows.Forms.Panel();
			this.btn_GroupSearch = new System.Windows.Forms.Button();
			this.cmbo_ItemFasl = new System.Windows.Forms.ComboBox();
			this.cmbo_ItemVahedSharh = new System.Windows.Forms.ComboBox();
			this.cmbo_Group = new System.Windows.Forms.ComboBox();
			this.Label7 = new System.Windows.Forms.Label();
			this.txt_ItemDarsad = new System.Windows.Forms.TextBox();
			this.Label5 = new System.Windows.Forms.Label();
			this.btn_ExitItem = new System.Windows.Forms.Button();
			this.btn_CopyItem = new System.Windows.Forms.Button();
			this.btn_DeleteItem = new System.Windows.Forms.Button();
			this.btn_InsertItem = new System.Windows.Forms.Button();
			this.cmbo_ItemNoa = new System.Windows.Forms.ComboBox();
			this.Label21 = new System.Windows.Forms.Label();
			this.txt_ItemBahavahed = new System.Windows.Forms.TextBox();
			this.Label30 = new System.Windows.Forms.Label();
			this.Label31 = new System.Windows.Forms.Label();
			this.btn_SaveItem = new System.Windows.Forms.Button();
			this.btn_VahedSearch = new System.Windows.Forms.Button();
			this.txt_ItemNo = new System.Windows.Forms.TextBox();
			this.Label35 = new System.Windows.Forms.Label();
			this.Label38 = new System.Windows.Forms.Label();
			this.Label43 = new System.Windows.Forms.Label();
			this.txt_ItemSharh = new System.Windows.Forms.TextBox();
			this.cmbo_FehrestItem = new System.Windows.Forms.ComboBox();
			this.dtg_Item = new System.Windows.Forms.DataGridView();
			this.tbp_Fosool = new System.Windows.Forms.TabPage();
			this.pnl_Fasl = new System.Windows.Forms.Panel();
			this.Btn_Insert = new System.Windows.Forms.Button();
			this.Btn_Copy = new System.Windows.Forms.Button();
			this.btn_Delete = new System.Windows.Forms.Button();
			this.Btn_Exit = new System.Windows.Forms.Button();
			this.Label1 = new System.Windows.Forms.Label();
			this.txt_ZaribComment = new System.Windows.Forms.TextBox();
			this.cmbo_ZaribCode = new System.Windows.Forms.ComboBox();
			this.Label2 = new System.Windows.Forms.Label();
			this.Btn_Save = new System.Windows.Forms.Button();
			this.Label3 = new System.Windows.Forms.Label();
			this.Label4 = new System.Windows.Forms.Label();
			this.txt_FaslCode = new System.Windows.Forms.TextBox();
			this.txt_FaslComment = new System.Windows.Forms.TextBox();
			this.cmbo_Fehrest = new System.Windows.Forms.ComboBox();
			this.dtg_Fosool = new System.Windows.Forms.DataGridView();
			this.tab_Fosool = new System.Windows.Forms.TabControl();
			this.tbp_Item.SuspendLayout();
			this.pnl_Filter.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).BeginInit();
			this.pnl_Item.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_Item).BeginInit();
			this.tbp_Fosool.SuspendLayout();
			this.pnl_Fasl.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_Fosool).BeginInit();
			this.tab_Fosool.SuspendLayout();
			base.SuspendLayout();
			this.tbp_Item.BackColor = System.Drawing.Color.DarkKhaki;
			this.tbp_Item.Controls.Add(this.pnl_Filter);
			this.tbp_Item.Controls.Add(this.pnl_Item);
			this.tbp_Item.Controls.Add(this.cmbo_FehrestItem);
			this.tbp_Item.Controls.Add(this.dtg_Item);
			this.tbp_Item.Location = new System.Drawing.Point(4, 27);
			this.tbp_Item.Name = "tbp_Item";
			this.tbp_Item.Padding = new System.Windows.Forms.Padding(3);
			this.tbp_Item.Size = new System.Drawing.Size(1197, 699);
			this.tbp_Item.TabIndex = 2;
			this.tbp_Item.Text = "          ایتم ها          ";
			this.pnl_Filter.BackColor = System.Drawing.Color.White;
			this.pnl_Filter.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnl_Filter.Controls.Add(this.Label10);
			this.pnl_Filter.Controls.Add(this.cmbo_GroupFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ItemVahedSharhFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ItemFaslFltr);
			this.pnl_Filter.Controls.Add(this.txt_ItemNoFltr);
			this.pnl_Filter.Controls.Add(this.cmbo_ItemNoaFltr);
			this.pnl_Filter.Controls.Add(this.txt_ItemBahavahedFltr);
			this.pnl_Filter.Controls.Add(this.txt_ItemSharhFltr);
			this.pnl_Filter.Controls.Add(this.btn_Filter);
			this.pnl_Filter.Controls.Add(this.PictureBox1);
			this.pnl_Filter.Location = new System.Drawing.Point(9, 49);
			this.pnl_Filter.Name = "pnl_Filter";
			this.pnl_Filter.Size = new System.Drawing.Size(1181, 49);
			this.pnl_Filter.TabIndex = 103;
			this.Label10.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.Label10.BackColor = System.Drawing.Color.White;
			this.Label10.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.Label10.Location = new System.Drawing.Point(1076, 2);
			this.Label10.Name = "Label10";
			this.Label10.Size = new System.Drawing.Size(60, 44);
			this.Label10.TabIndex = 155;
			this.Label10.Text = "ردیف";
			this.Label10.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.cmbo_GroupFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_GroupFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_GroupFltr.FormattingEnabled = true;
			this.cmbo_GroupFltr.Location = new System.Drawing.Point(21, 25);
			this.cmbo_GroupFltr.Name = "cmbo_GroupFltr";
			this.cmbo_GroupFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_GroupFltr.Size = new System.Drawing.Size(224, 26);
			this.cmbo_GroupFltr.TabIndex = 80;
			this.cmbo_ItemVahedSharhFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemVahedSharhFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ItemVahedSharhFltr.FormattingEnabled = true;
			this.cmbo_ItemVahedSharhFltr.Location = new System.Drawing.Point(397, 26);
			this.cmbo_ItemVahedSharhFltr.Name = "cmbo_ItemVahedSharhFltr";
			this.cmbo_ItemVahedSharhFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemVahedSharhFltr.Size = new System.Drawing.Size(79, 26);
			this.cmbo_ItemVahedSharhFltr.TabIndex = 77;
			this.cmbo_ItemFaslFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemFaslFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ItemFaslFltr.FormattingEnabled = true;
			this.cmbo_ItemFaslFltr.Location = new System.Drawing.Point(477, 26);
			this.cmbo_ItemFaslFltr.Name = "cmbo_ItemFaslFltr";
			this.cmbo_ItemFaslFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemFaslFltr.Size = new System.Drawing.Size(39, 26);
			this.cmbo_ItemFaslFltr.TabIndex = 76;
			this.txt_ItemNoFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemNoFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ItemNoFltr.Location = new System.Drawing.Point(1017, 26);
			this.txt_ItemNoFltr.Name = "txt_ItemNoFltr";
			this.txt_ItemNoFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemNoFltr.Size = new System.Drawing.Size(58, 26);
			this.txt_ItemNoFltr.TabIndex = 74;
			this.cmbo_ItemNoaFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemNoaFltr.ForeColor = System.Drawing.Color.Red;
			this.cmbo_ItemNoaFltr.FormattingEnabled = true;
			this.cmbo_ItemNoaFltr.Location = new System.Drawing.Point(246, 25);
			this.cmbo_ItemNoaFltr.Name = "cmbo_ItemNoaFltr";
			this.cmbo_ItemNoaFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemNoaFltr.Size = new System.Drawing.Size(80, 26);
			this.cmbo_ItemNoaFltr.TabIndex = 79;
			this.txt_ItemBahavahedFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemBahavahedFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ItemBahavahedFltr.Location = new System.Drawing.Point(327, 26);
			this.txt_ItemBahavahedFltr.Name = "txt_ItemBahavahedFltr";
			this.txt_ItemBahavahedFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemBahavahedFltr.Size = new System.Drawing.Size(69, 26);
			this.txt_ItemBahavahedFltr.TabIndex = 78;
			this.txt_ItemSharhFltr.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemSharhFltr.ForeColor = System.Drawing.Color.Red;
			this.txt_ItemSharhFltr.Location = new System.Drawing.Point(517, 26);
			this.txt_ItemSharhFltr.Name = "txt_ItemSharhFltr";
			this.txt_ItemSharhFltr.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemSharhFltr.Size = new System.Drawing.Size(499, 26);
			this.txt_ItemSharhFltr.TabIndex = 75;
			this.btn_Filter.BackColor = System.Drawing.Color.WhiteSmoke;
			this.btn_Filter.Font = new System.Drawing.Font("Times New Roman", 9.75f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.btn_Filter.ForeColor = System.Drawing.Color.Black;
			this.btn_Filter.Location = new System.Drawing.Point(1135, 1);
			this.btn_Filter.Name = "btn_Filter";
			this.btn_Filter.Size = new System.Drawing.Size(45, 46);
			this.btn_Filter.TabIndex = 44;
			this.btn_Filter.UseVisualStyleBackColor = false;
			this.PictureBox1.Image = (System.Drawing.Image)resources.GetObject("PictureBox1.Image");
			this.PictureBox1.Location = new System.Drawing.Point(18, 0);
			this.PictureBox1.Name = "PictureBox1";
			this.PictureBox1.Size = new System.Drawing.Size(1156, 25);
			this.PictureBox1.TabIndex = 75;
			this.PictureBox1.TabStop = false;
			this.pnl_Item.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnl_Item.Controls.Add(this.btn_GroupSearch);
			this.pnl_Item.Controls.Add(this.cmbo_ItemFasl);
			this.pnl_Item.Controls.Add(this.cmbo_ItemVahedSharh);
			this.pnl_Item.Controls.Add(this.cmbo_Group);
			this.pnl_Item.Controls.Add(this.Label7);
			this.pnl_Item.Controls.Add(this.txt_ItemDarsad);
			this.pnl_Item.Controls.Add(this.Label5);
			this.pnl_Item.Controls.Add(this.btn_ExitItem);
			this.pnl_Item.Controls.Add(this.btn_CopyItem);
			this.pnl_Item.Controls.Add(this.btn_DeleteItem);
			this.pnl_Item.Controls.Add(this.btn_InsertItem);
			this.pnl_Item.Controls.Add(this.cmbo_ItemNoa);
			this.pnl_Item.Controls.Add(this.Label21);
			this.pnl_Item.Controls.Add(this.txt_ItemBahavahed);
			this.pnl_Item.Controls.Add(this.Label30);
			this.pnl_Item.Controls.Add(this.Label31);
			this.pnl_Item.Controls.Add(this.btn_SaveItem);
			this.pnl_Item.Controls.Add(this.btn_VahedSearch);
			this.pnl_Item.Controls.Add(this.txt_ItemNo);
			this.pnl_Item.Controls.Add(this.Label35);
			this.pnl_Item.Controls.Add(this.Label38);
			this.pnl_Item.Controls.Add(this.Label43);
			this.pnl_Item.Controls.Add(this.txt_ItemSharh);
			this.pnl_Item.Location = new System.Drawing.Point(10, 539);
			this.pnl_Item.Name = "pnl_Item";
			this.pnl_Item.Size = new System.Drawing.Size(1178, 156);
			this.pnl_Item.TabIndex = 111;
			this.btn_GroupSearch.Image = (System.Drawing.Image)resources.GetObject("btn_GroupSearch.Image");
			this.btn_GroupSearch.Location = new System.Drawing.Point(13, 62);
			this.btn_GroupSearch.Name = "btn_GroupSearch";
			this.btn_GroupSearch.Size = new System.Drawing.Size(25, 21);
			this.btn_GroupSearch.TabIndex = 132;
			this.btn_GroupSearch.UseVisualStyleBackColor = true;
			this.btn_GroupSearch.Visible = false;
			this.cmbo_ItemFasl.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemFasl.FormattingEnabled = true;
			this.cmbo_ItemFasl.Location = new System.Drawing.Point(306, 33);
			this.cmbo_ItemFasl.Name = "cmbo_ItemFasl";
			this.cmbo_ItemFasl.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemFasl.Size = new System.Drawing.Size(100, 26);
			this.cmbo_ItemFasl.TabIndex = 5;
			this.cmbo_ItemVahedSharh.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemVahedSharh.FormattingEnabled = true;
			this.cmbo_ItemVahedSharh.Location = new System.Drawing.Point(306, 5);
			this.cmbo_ItemVahedSharh.Name = "cmbo_ItemVahedSharh";
			this.cmbo_ItemVahedSharh.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemVahedSharh.Size = new System.Drawing.Size(100, 26);
			this.cmbo_ItemVahedSharh.TabIndex = 3;
			this.cmbo_Group.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_Group.FormattingEnabled = true;
			this.cmbo_Group.Location = new System.Drawing.Point(38, 62);
			this.cmbo_Group.Name = "cmbo_Group";
			this.cmbo_Group.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_Group.Size = new System.Drawing.Size(368, 26);
			this.cmbo_Group.TabIndex = 7;
			this.Label7.AutoSize = true;
			this.Label7.Location = new System.Drawing.Point(405, 66);
			this.Label7.Name = "Label7";
			this.Label7.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label7.Size = new System.Drawing.Size(36, 15);
			this.Label7.TabIndex = 131;
			this.Label7.Text = ":  گروه";
			this.txt_ItemDarsad.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemDarsad.Location = new System.Drawing.Point(40, 91);
			this.txt_ItemDarsad.Name = "txt_ItemDarsad";
			this.txt_ItemDarsad.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemDarsad.Size = new System.Drawing.Size(1036, 26);
			this.txt_ItemDarsad.TabIndex = 8;
			this.Label5.AutoSize = true;
			this.Label5.Location = new System.Drawing.Point(1074, 98);
			this.Label5.Name = "Label5";
			this.Label5.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label5.Size = new System.Drawing.Size(73, 15);
			this.Label5.TabIndex = 129;
			this.Label5.Text = ": درصد نسبت به";
			this.btn_ExitItem.Location = new System.Drawing.Point(39, 122);
			this.btn_ExitItem.Name = "btn_ExitItem";
			this.btn_ExitItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_ExitItem.Size = new System.Drawing.Size(100, 27);
			this.btn_ExitItem.TabIndex = 13;
			this.btn_ExitItem.Text = "بازگشت";
			this.btn_ExitItem.UseVisualStyleBackColor = true;
			this.btn_CopyItem.Location = new System.Drawing.Point(529, 122);
			this.btn_CopyItem.Name = "btn_CopyItem";
			this.btn_CopyItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_CopyItem.Size = new System.Drawing.Size(100, 27);
			this.btn_CopyItem.TabIndex = 11;
			this.btn_CopyItem.Text = "(Clt+C) کپی";
			this.btn_CopyItem.UseVisualStyleBackColor = true;
			this.btn_DeleteItem.Location = new System.Drawing.Point(272, 122);
			this.btn_DeleteItem.Name = "btn_DeleteItem";
			this.btn_DeleteItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_DeleteItem.Size = new System.Drawing.Size(100, 27);
			this.btn_DeleteItem.TabIndex = 12;
			this.btn_DeleteItem.Text = "(Del) حذف";
			this.btn_DeleteItem.UseVisualStyleBackColor = true;
			this.btn_InsertItem.Location = new System.Drawing.Point(785, 122);
			this.btn_InsertItem.Name = "btn_InsertItem";
			this.btn_InsertItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_InsertItem.Size = new System.Drawing.Size(100, 27);
			this.btn_InsertItem.TabIndex = 10;
			this.btn_InsertItem.Text = "(Ins) ایجاد ";
			this.btn_InsertItem.UseVisualStyleBackColor = true;
			this.cmbo_ItemNoa.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ItemNoa.FormattingEnabled = true;
			this.cmbo_ItemNoa.Location = new System.Drawing.Point(40, 33);
			this.cmbo_ItemNoa.Name = "cmbo_ItemNoa";
			this.cmbo_ItemNoa.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ItemNoa.Size = new System.Drawing.Size(110, 26);
			this.cmbo_ItemNoa.TabIndex = 6;
			this.Label21.AutoSize = true;
			this.Label21.Location = new System.Drawing.Point(407, 38);
			this.Label21.Name = "Label21";
			this.Label21.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label21.Size = new System.Drawing.Size(35, 15);
			this.Label21.TabIndex = 116;
			this.Label21.Text = ":  فصل";
			this.txt_ItemBahavahed.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemBahavahed.Location = new System.Drawing.Point(40, 5);
			this.txt_ItemBahavahed.Name = "txt_ItemBahavahed";
			this.txt_ItemBahavahed.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemBahavahed.Size = new System.Drawing.Size(110, 26);
			this.txt_ItemBahavahed.TabIndex = 4;
			this.Label30.AutoSize = true;
			this.Label30.Location = new System.Drawing.Point(148, 10);
			this.Label30.Name = "Label30";
			this.Label30.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label30.Size = new System.Drawing.Size(54, 15);
			this.Label30.TabIndex = 110;
			this.Label30.Text = ": بهای واحد";
			this.Label31.AutoSize = true;
			this.Label31.Location = new System.Drawing.Point(149, 38);
			this.Label31.Name = "Label31";
			this.Label31.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label31.Size = new System.Drawing.Size(47, 15);
			this.Label31.TabIndex = 108;
			this.Label31.Text = ":  نوع ایتم";
			this.btn_SaveItem.Location = new System.Drawing.Point(1038, 122);
			this.btn_SaveItem.Name = "btn_SaveItem";
			this.btn_SaveItem.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_SaveItem.Size = new System.Drawing.Size(100, 27);
			this.btn_SaveItem.TabIndex = 9;
			this.btn_SaveItem.Text = "(F2) ذخیره ";
			this.btn_SaveItem.UseVisualStyleBackColor = true;
			this.btn_VahedSearch.Image = (System.Drawing.Image)resources.GetObject("btn_VahedSearch.Image");
			this.btn_VahedSearch.Location = new System.Drawing.Point(280, 5);
			this.btn_VahedSearch.Name = "btn_VahedSearch";
			this.btn_VahedSearch.Size = new System.Drawing.Size(25, 21);
			this.btn_VahedSearch.TabIndex = 83;
			this.btn_VahedSearch.UseVisualStyleBackColor = true;
			this.btn_VahedSearch.Visible = false;
			this.txt_ItemNo.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ItemNo.Location = new System.Drawing.Point(1009, 9);
			this.txt_ItemNo.Name = "txt_ItemNo";
			this.txt_ItemNo.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemNo.Size = new System.Drawing.Size(100, 26);
			this.txt_ItemNo.TabIndex = 1;
			this.Label35.AutoSize = true;
			this.Label35.Location = new System.Drawing.Point(1108, 10);
			this.Label35.Name = "Label35";
			this.Label35.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label35.Size = new System.Drawing.Size(29, 15);
			this.Label35.TabIndex = 78;
			this.Label35.Text = ":  ایتم";
			this.Label38.AutoSize = true;
			this.Label38.Location = new System.Drawing.Point(405, 10);
			this.Label38.Name = "Label38";
			this.Label38.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label38.Size = new System.Drawing.Size(35, 15);
			this.Label38.TabIndex = 21;
			this.Label38.Text = ":  واحد";
			this.Label43.AutoSize = true;
			this.Label43.Location = new System.Drawing.Point(947, 10);
			this.Label43.Name = "Label43";
			this.Label43.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Label43.Size = new System.Drawing.Size(36, 15);
			this.Label43.TabIndex = 20;
			this.Label43.Text = ":  شرح";
			this.txt_ItemSharh.Font = new System.Drawing.Font("B Yekan", 9f);
			this.txt_ItemSharh.Location = new System.Drawing.Point(490, 5);
			this.txt_ItemSharh.Multiline = true;
			this.txt_ItemSharh.Name = "txt_ItemSharh";
			this.txt_ItemSharh.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ItemSharh.Size = new System.Drawing.Size(458, 80);
			this.txt_ItemSharh.TabIndex = 2;
			this.cmbo_FehrestItem.BackColor = System.Drawing.SystemColors.Window;
			this.cmbo_FehrestItem.Font = new System.Drawing.Font("B Titr", 12f, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_FehrestItem.FormattingEnabled = true;
			this.cmbo_FehrestItem.Location = new System.Drawing.Point(213, 6);
			this.cmbo_FehrestItem.Name = "cmbo_FehrestItem";
			this.cmbo_FehrestItem.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_FehrestItem.Size = new System.Drawing.Size(800, 37);
			this.cmbo_FehrestItem.TabIndex = 106;
			this.dtg_Item.AllowUserToAddRows = false;
			this.dtg_Item.AllowUserToDeleteRows = false;
			this.dtg_Item.AllowUserToOrderColumns = true;
			this.dtg_Item.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
			this.dtg_Item.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			dataGridViewCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dtg_Item.DefaultCellStyle = dataGridViewCellStyle;
			this.dtg_Item.GridColor = System.Drawing.SystemColors.ButtonFace;
			this.dtg_Item.Location = new System.Drawing.Point(9, 76);
			this.dtg_Item.Name = "dtg_Item";
			this.dtg_Item.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			dataGridViewCellStyle2.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.dtg_Item.RowsDefaultCellStyle = dataGridViewCellStyle2;
			this.dtg_Item.RowTemplate.Height = 44;
			this.dtg_Item.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
			this.dtg_Item.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dtg_Item.Size = new System.Drawing.Size(1180, 461);
			this.dtg_Item.TabIndex = 101;
			this.tbp_Fosool.BackColor = System.Drawing.Color.Thistle;
			this.tbp_Fosool.Controls.Add(this.pnl_Fasl);
			this.tbp_Fosool.Controls.Add(this.cmbo_Fehrest);
			this.tbp_Fosool.Controls.Add(this.dtg_Fosool);
			this.tbp_Fosool.ForeColor = System.Drawing.Color.Black;
			this.tbp_Fosool.Location = new System.Drawing.Point(4, 27);
			this.tbp_Fosool.Name = "tbp_Fosool";
			this.tbp_Fosool.Padding = new System.Windows.Forms.Padding(3);
			this.tbp_Fosool.Size = new System.Drawing.Size(1197, 699);
			this.tbp_Fosool.TabIndex = 1;
			this.tbp_Fosool.Text = "          فصول          ";
			this.pnl_Fasl.BackColor = System.Drawing.Color.Thistle;
			this.pnl_Fasl.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
			this.pnl_Fasl.Controls.Add(this.Btn_Insert);
			this.pnl_Fasl.Controls.Add(this.Btn_Copy);
			this.pnl_Fasl.Controls.Add(this.btn_Delete);
			this.pnl_Fasl.Controls.Add(this.Btn_Exit);
			this.pnl_Fasl.Controls.Add(this.Label1);
			this.pnl_Fasl.Controls.Add(this.txt_ZaribComment);
			this.pnl_Fasl.Controls.Add(this.cmbo_ZaribCode);
			this.pnl_Fasl.Controls.Add(this.Label2);
			this.pnl_Fasl.Controls.Add(this.Btn_Save);
			this.pnl_Fasl.Controls.Add(this.Label3);
			this.pnl_Fasl.Controls.Add(this.Label4);
			this.pnl_Fasl.Controls.Add(this.txt_FaslCode);
			this.pnl_Fasl.Controls.Add(this.txt_FaslComment);
			this.pnl_Fasl.Location = new System.Drawing.Point(9, 548);
			this.pnl_Fasl.Name = "pnl_Fasl";
			this.pnl_Fasl.Size = new System.Drawing.Size(1180, 142);
			this.pnl_Fasl.TabIndex = 96;
			this.Btn_Insert.Location = new System.Drawing.Point(788, 96);
			this.Btn_Insert.Name = "Btn_Insert";
			this.Btn_Insert.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Insert.Size = new System.Drawing.Size(71, 28);
			this.Btn_Insert.TabIndex = 6;
			this.Btn_Insert.Text = "(Ins) ایجاد ";
			this.Btn_Insert.UseVisualStyleBackColor = true;
			this.Btn_Copy.Location = new System.Drawing.Point(570, 96);
			this.Btn_Copy.Name = "Btn_Copy";
			this.Btn_Copy.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Copy.Size = new System.Drawing.Size(71, 28);
			this.Btn_Copy.TabIndex = 7;
			this.Btn_Copy.Text = "(Clt+C) کپی";
			this.Btn_Copy.UseVisualStyleBackColor = true;
			this.btn_Delete.Enabled = false;
			this.btn_Delete.Location = new System.Drawing.Point(344, 96);
			this.btn_Delete.Name = "btn_Delete";
			this.btn_Delete.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.btn_Delete.Size = new System.Drawing.Size(71, 28);
			this.btn_Delete.TabIndex = 8;
			this.btn_Delete.Text = "(Del) حذف";
			this.btn_Delete.UseVisualStyleBackColor = true;
			this.Btn_Exit.Location = new System.Drawing.Point(129, 96);
			this.Btn_Exit.Name = "Btn_Exit";
			this.Btn_Exit.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Exit.Size = new System.Drawing.Size(71, 28);
			this.Btn_Exit.TabIndex = 9;
			this.Btn_Exit.Text = "بازگشت";
			this.Btn_Exit.UseVisualStyleBackColor = true;
			this.Label1.AutoSize = true;
			this.Label1.Location = new System.Drawing.Point(227, 15);
			this.Label1.Name = "Label1";
			this.Label1.Size = new System.Drawing.Size(70, 15);
			this.Label1.TabIndex = 114;
			this.Label1.Text = "شرح کد ضریب";
			this.txt_ZaribComment.Enabled = false;
			this.txt_ZaribComment.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_ZaribComment.Location = new System.Drawing.Point(26, 31);
			this.txt_ZaribComment.Name = "txt_ZaribComment";
			this.txt_ZaribComment.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_ZaribComment.Size = new System.Drawing.Size(376, 26);
			this.txt_ZaribComment.TabIndex = 4;
			this.cmbo_ZaribCode.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cmbo_ZaribCode.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_ZaribCode.FormattingEnabled = true;
			this.cmbo_ZaribCode.Location = new System.Drawing.Point(410, 31);
			this.cmbo_ZaribCode.Name = "cmbo_ZaribCode";
			this.cmbo_ZaribCode.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_ZaribCode.Size = new System.Drawing.Size(76, 26);
			this.cmbo_ZaribCode.TabIndex = 3;
			this.Label2.AutoSize = true;
			this.Label2.Location = new System.Drawing.Point(429, 15);
			this.Label2.Name = "Label2";
			this.Label2.Size = new System.Drawing.Size(47, 15);
			this.Label2.TabIndex = 90;
			this.Label2.Text = "کد ضریب";
			this.Btn_Save.Location = new System.Drawing.Point(994, 96);
			this.Btn_Save.Name = "Btn_Save";
			this.Btn_Save.RightToLeft = System.Windows.Forms.RightToLeft.No;
			this.Btn_Save.Size = new System.Drawing.Size(71, 28);
			this.Btn_Save.TabIndex = 5;
			this.Btn_Save.Text = "(F2) ذخیره ";
			this.Btn_Save.UseVisualStyleBackColor = true;
			this.Label3.AutoSize = true;
			this.Label3.Location = new System.Drawing.Point(793, 15);
			this.Label3.Name = "Label3";
			this.Label3.Size = new System.Drawing.Size(27, 15);
			this.Label3.TabIndex = 95;
			this.Label3.Text = "شرح";
			this.Label4.AutoSize = true;
			this.Label4.Location = new System.Drawing.Point(1106, 15);
			this.Label4.Name = "Label4";
			this.Label4.Size = new System.Drawing.Size(26, 15);
			this.Label4.TabIndex = 94;
			this.Label4.Text = "فصل";
			this.txt_FaslCode.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_FaslCode.Location = new System.Drawing.Point(1099, 31);
			this.txt_FaslCode.Name = "txt_FaslCode";
			this.txt_FaslCode.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_FaslCode.Size = new System.Drawing.Size(50, 26);
			this.txt_FaslCode.TabIndex = 1;
			this.txt_FaslComment.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.txt_FaslComment.Location = new System.Drawing.Point(493, 31);
			this.txt_FaslComment.Name = "txt_FaslComment";
			this.txt_FaslComment.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.txt_FaslComment.Size = new System.Drawing.Size(600, 26);
			this.txt_FaslComment.TabIndex = 2;
			this.cmbo_Fehrest.BackColor = System.Drawing.SystemColors.MenuHighlight;
			this.cmbo_Fehrest.Font = new System.Drawing.Font("Microsoft Sans Serif", 12f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.cmbo_Fehrest.FormattingEnabled = true;
			this.cmbo_Fehrest.Location = new System.Drawing.Point(255, 18);
			this.cmbo_Fehrest.Name = "cmbo_Fehrest";
			this.cmbo_Fehrest.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.cmbo_Fehrest.Size = new System.Drawing.Size(700, 28);
			this.cmbo_Fehrest.TabIndex = 95;
			this.dtg_Fosool.AllowUserToAddRows = false;
			this.dtg_Fosool.AllowUserToDeleteRows = false;
			this.dtg_Fosool.AllowUserToOrderColumns = true;
			this.dtg_Fosool.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
			this.dtg_Fosool.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Window;
			dataGridViewCellStyle3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
			dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
			this.dtg_Fosool.DefaultCellStyle = dataGridViewCellStyle3;
			this.dtg_Fosool.EditMode = System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.dtg_Fosool.Location = new System.Drawing.Point(9, 52);
			this.dtg_Fosool.Name = "dtg_Fosool";
			dataGridViewCellStyle4.Font = new System.Drawing.Font("B Yekan", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 178);
			this.dtg_Fosool.RowsDefaultCellStyle = dataGridViewCellStyle4;
			this.dtg_Fosool.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
			this.dtg_Fosool.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.dtg_Fosool.Size = new System.Drawing.Size(1180, 489);
			this.dtg_Fosool.TabIndex = 97;
			this.tab_Fosool.Appearance = System.Windows.Forms.TabAppearance.Buttons;
			this.tab_Fosool.Controls.Add(this.tbp_Fosool);
			this.tab_Fosool.Controls.Add(this.tbp_Item);
			this.tab_Fosool.Font = new System.Drawing.Font("Microsoft Sans Serif", 9f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, 0);
			this.tab_Fosool.Location = new System.Drawing.Point(0, 0);
			this.tab_Fosool.Name = "tab_Fosool";
			this.tab_Fosool.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.tab_Fosool.RightToLeftLayout = true;
			this.tab_Fosool.SelectedIndex = 0;
			this.tab_Fosool.Size = new System.Drawing.Size(1205, 730);
			this.tab_Fosool.TabIndex = 15;
			base.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.AutoScroll = true;
			base.ClientSize = new System.Drawing.Size(1204, 741);
			base.ControlBox = false;
			base.Controls.Add(this.tab_Fosool);
			base.Name = "Frm_FehrestDetail";
			this.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
			this.RightToLeftLayout = true;
			base.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "اطلاعات فهارس بها";
			this.tbp_Item.ResumeLayout(false);
			this.pnl_Filter.ResumeLayout(false);
			this.pnl_Filter.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.PictureBox1).EndInit();
			this.pnl_Item.ResumeLayout(false);
			this.pnl_Item.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_Item).EndInit();
			this.tbp_Fosool.ResumeLayout(false);
			this.pnl_Fasl.ResumeLayout(false);
			this.pnl_Fasl.PerformLayout();
			((System.ComponentModel.ISupportInitialize)this.dtg_Fosool).EndInit();
			this.tab_Fosool.ResumeLayout(false);
			base.ResumeLayout(false);

            this.tbp_Item.Enter += new System.EventHandler(this.tbp_Item_Enter);
            this.cmbo_FehrestItem.SelectedIndexChanged += new System.EventHandler(this.cmbo_FehrestItem_SelectedIndexChanged);
            this.cmbo_FehrestItem.TextChanged += new System.EventHandler(this.cmbo_FehrestItem_TextChanged);
            this.txt_ItemNoFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ItemNoFltr_KeyDown);
            this.cmbo_ItemNoaFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_ItemNoaFltr_SelectedIndexChanged);
            this.txt_ItemBahavahedFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ItemBahavahedFltr_KeyDown);
            this.txt_ItemSharhFltr.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txt_ItemSharhFltr_KeyDown);
            this.btn_Filter.Click += new System.EventHandler(this.btn_Filter_Click);
            this.dtg_Item.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Item_CellClick);
            this.dtg_Item.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Item_CellContentClick);
            this.dtg_Item.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Item_CellDoubleClick);
            this.dtg_Item.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dtg_Item_KeyDown);
            this.dtg_Item.SelectionChanged += new System.EventHandler(this.dtg_Item_SelectionChanged);
            this.tbp_Fosool.Enter += new System.EventHandler(this.tbp_Fosool_Enter);
            this.tbp_Fosool.Click += new System.EventHandler(this.tbp_Fosool_Click);
            this.cmbo_Fehrest.SelectedIndexChanged += new System.EventHandler(this.cmbo_Fehrest_SelectedIndexChanged);
            this.dtg_Fosool.CellClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Fosool_CellClick);
            this.dtg_Fosool.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtg_Fosool_CellContentClick);
            this.dtg_Fosool.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dtg_Fosool_KeyDown);
            this.dtg_Fosool.SelectionChanged += new System.EventHandler(this.dtg_Fosool_SelectionChanged);
            this.cmbo_ZaribCode.GotFocus += new System.EventHandler(this.cmbo_ZaribCode_GotFocus);
            this.cmbo_ZaribCode.SelectedIndexChanged += new System.EventHandler(this.cmbo_ZaribCode_SelectedIndexChanged);
            this.cmbo_ZaribCode.TextChanged += new System.EventHandler(this.cmbo_ZaribCode_TextChanged);
            this.Btn_Save.Click += new System.EventHandler(this.Btn_Save_Click);
            this.txt_FaslCode.GotFocus += new System.EventHandler(this.txt_FaslCode_GotFocus);
            this.txt_FaslCode.TextChanged += new System.EventHandler(this.txt_FaslCode_TextChanged);
            this.txt_FaslComment.GotFocus += new System.EventHandler(this.txt_FaslComment_GotFocus);
            this.txt_FaslComment.TextChanged += new System.EventHandler(this.txt_FaslComment_TextChanged);
            this.cmbo_ItemNoa.TextChanged += new System.EventHandler(this.cmbo_ItemNoa_TextChanged);
            this.cmbo_ItemNoa.GotFocus += new System.EventHandler(this.cmbo_ItemNoa_GotFocus);
            this.cmbo_ItemNoa.SelectedIndexChanged += new System.EventHandler(this.cmbo_ItemNoa_SelectedIndexChanged);
            this.txt_ItemBahavahed.GotFocus += new System.EventHandler(this.txt_ItemBahavahed_GotFocus);
            this.txt_ItemBahavahed.TextChanged += new System.EventHandler(this.txt_ItemBahavahed_TextChanged);
            this.btn_SaveItem.Click += new System.EventHandler(this.btn_SaveItem_Click);
            this.btn_VahedSearch.Click += new System.EventHandler(this.btn_Search_Click);
            this.txt_ItemNo.GotFocus += new System.EventHandler(this.txt_ItemNo_GotFocus);
            this.txt_ItemNo.TextChanged += new System.EventHandler(this.txt_ItemNo_TextChanged);
            this.txt_ItemSharh.GotFocus += new System.EventHandler(this.txt_ItemSharh_GotFocus);
            this.txt_ItemSharh.TextChanged += new System.EventHandler(this.txt_ItemSharh_TextChanged);
            this.cmbo_ItemFaslFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_ItemFaslFltr_SelectedIndexChanged);
            this.cmbo_ItemVahedSharhFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_ItemVahedSharhFltr_SelectedIndexChanged);
            this.txt_ZaribComment.GotFocus += new System.EventHandler(this.txt_ZaribComment_GotFocus);
            this.Btn_Insert.Click += new System.EventHandler(this.Btn_Insert_Click);
            this.Btn_Copy.Click += new System.EventHandler(this.Btn_Copy_Click);
            this.btn_Delete.Click += new System.EventHandler(this.btn_Delete_Click);
            this.Btn_Exit.Click += new System.EventHandler(this.Btn_Exit_Click);
            this.btn_ExitItem.Click += new System.EventHandler(this.btn_ExitItem_Click);
            this.btn_CopyItem.Click += new System.EventHandler(this.btn_CopyItem_Click);
            this.btn_DeleteItem.Click += new System.EventHandler(this.btn_DeleteItem_Click);
            this.btn_InsertItem.Click += new System.EventHandler(this.btn_InsertItem_Click);
            this.txt_ItemDarsad.GotFocus += new System.EventHandler(this.txt_ItemDarsad_GotFocus);
            this.txt_ItemDarsad.TextChanged += new System.EventHandler(this.txt_ItemDarsad_TextChanged);
            this.cmbo_GroupFltr.SelectedIndexChanged += new System.EventHandler(this.cmbo_GroupFltr_SelectedIndexChanged);
            this.cmbo_ItemVahedSharh.GotFocus += new System.EventHandler(this.cmbo_ItemVahedSharh_GotFocus);
            this.cmbo_ItemVahedSharh.TextChanged += new System.EventHandler(this.cmbo_ItemVahedSharh_TextChanged);
            this.cmbo_ItemFasl.GotFocus += new System.EventHandler(this.cmbo_ItemFasl_GotFocus);
            this.cmbo_ItemFasl.TextChanged += new System.EventHandler(this.cmbo_ItemFasl_TextChanged);
            this.btn_GroupSearch.Click += new System.EventHandler(this.btn_GroupSearch_Click);
        }
    }
}
